packages:
  - server
  - app/mweb
  - portals/admin
  - website/main-website
  - portals/partners-app
  - website/partners-website
  - portals/ads-portal
  - website/ads-website
  - portals/crm
  - portals/finance
  - portals/tech
  - portals/support
  - portals/website-app
  - portals/legal
  - portals/ai
  - portals/products
  - portals/marketing
  - portals/onboarding
  - portals/hr
  - portals/employee
  - website/status-website
  - packages/*
