packages:
  - server
  - mweb-app
  - admin
  - website
  - partners/partners-app
  - partners/partners-website
  - ads/ads-portal
  - ads/ads-website
  - crm
  - finance
  - tech
  - support
  - website-app
  - legal
  - ai
  - products
  - marketing
  - onboarding
  - hr
  - employee
  - status
  - packages/*