import gql from 'graphql-tag';
import { userTypeDefs } from '@modules/access/user/user.schema';
import { userResolvers } from '@modules/access/user/user.resolver';
import { verificationTypeDefs } from '@modules/access/verification/verification.schema';
import { verificationResolvers } from '@modules/access/verification/verification.resolver';
import { rbacTypeDefs } from '@modules/access/rbac/rbac.schema';
import { rbacResolvers } from '@modules/access/rbac/rbac.resolver';
import { settingsTypeDefs } from '@modules/platform/settings/settings.schema';
import { settingsResolvers } from '@modules/platform/settings/settings.resolver';
import { categoryTypeDefs } from '@modules/pods/category/category.schema';
import { categoryResolvers } from '@modules/pods/category/category.resolver';
import { locationTypeDefs } from '@modules/platform/location/location.schema';
import { locationResolvers } from '@modules/platform/location/location.resolver';
import { clubTypeDefs } from '@modules/pods/club/club.schema';
import { clubResolvers } from '@modules/pods/club/club.resolver';
import { podTypeDefs } from '@modules/pods/pod/pod.schema';
import { podResolvers } from '@modules/pods/pod/pod.resolver';
import { clubAdminTypeDefs } from '@modules/pods/clubAdmin/clubAdmin.schema';
import { clubAdminResolvers } from '@modules/pods/clubAdmin/clubAdmin.resolver';
import { notificationTypeDefs } from '@modules/engagement/notification/notification.schema';
import { notificationResolvers } from '@modules/engagement/notification/notification.resolver';
import { referralTypeDefs } from '@modules/engagement/referral/referral.schema';
import { referralResolvers } from '@modules/engagement/referral/referral.resolver';
import { interviewTypeDefs } from '@modules/pods/interview/interview.schema';
import { interviewResolvers } from '@modules/pods/interview/interview.resolver';
import { faqTypeDefs } from '@modules/support/faq/faq.schema';
import { faqResolvers } from '@modules/support/faq/faq.resolver';
import { financeTypeDefs } from '@modules/finance/finance/finance.schema';
import { financeResolvers } from '@modules/finance/finance/finance.resolver';
import { paymentTypeDefs } from '@modules/finance/payment/payment.schema';
import { paymentResolvers } from '@modules/finance/payment/payment.resolver';
import { productOrderTypeDefs } from '@modules/commerce/productOrder/productOrder.schema';
import { productOrderResolvers } from '@modules/commerce/productOrder/productOrder.resolver';
import { brandPickupLocationTypeDefs } from '@modules/venues/brandPickupLocation/brandPickupLocation.schema';
import { brandPickupLocationResolvers } from '@modules/venues/brandPickupLocation/brandPickupLocation.resolver';
import { couponTypeDefs } from '@modules/finance/coupon/coupon.schema';
import { couponResolvers } from '@modules/finance/coupon/coupon.resolver';
import { expenseTypeDefs } from '@modules/finance/expense/expense.schema';
import { expenseResolvers } from '@modules/finance/expense/expense.resolver';
import { walletTypeDefs } from '@modules/finance/wallet/wallet.schema';
import { walletResolvers } from '@modules/finance/wallet/wallet.resolver';
import { founderTypeDefs } from '@modules/finance/founder/founder.schema';
import { founderResolvers } from '@modules/finance/founder/founder.resolver';
import { eventTicketTypeDefs } from '@modules/pods/ticket/ticket.schema';
import { eventTicketResolvers } from '@modules/pods/ticket/ticket.resolver';
import { aiTypeDefs } from '@modules/ai/ai/ai.schema';
import { aiResolvers } from '@modules/ai/ai/ai.resolver';
import { aiPromptTypeDefs } from '@modules/ai/prompt/prompt.schema';
import { aiPromptResolvers } from '@modules/ai/prompt/prompt.resolver';
import { postTypeDefs } from '@modules/engagement/post/post.schema';
import { postResolvers } from '@modules/engagement/post/post.resolver';
import { policyTypeDefs } from '@modules/content/policy/policy.schema';
import { policyResolvers } from '@modules/content/policy/policy.resolver';
import { podIdeaTypeDefs } from '@modules/pods/podIdea/podIdea.schema';
import { podIdeaResolvers } from '@modules/pods/podIdea/podIdea.resolver';
import { uploadTypeDefs } from '@modules/platform/upload/upload.schema';
import { uploadResolvers } from '@modules/platform/upload/upload.resolver';
import { emailTemplateTypeDefs } from '@modules/content/emailTemplate/emailTemplate.schema';
import { emailTemplateResolvers } from '@modules/content/emailTemplate/emailTemplate.resolver';
import { podMemberTypeDefs } from '@modules/pods/podMember/podMember.schema';
import { podMemberResolvers } from '@modules/pods/podMember/podMember.resolver';
import { badgeTypeDefs } from '@modules/engagement/badge/badge.schema';
import { badgeResolvers } from '@modules/engagement/badge/badge.resolver';
import { venueTypeDefs } from '@modules/venues/venue/venue.schema';
import { venueResolvers } from '@modules/venues/venue/venue.resolver';
import { hostTypeDefs } from '@modules/venues/host/host.schema';
import { hostResolvers } from '@modules/venues/host/host.resolver';
import { chatTypeDefs } from '@modules/engagement/chat/chat.schema';
import { chatResolvers } from '@modules/engagement/chat/chat.resolver';
import { newsletterTypeDefs } from '@modules/crm/newsletter/newsletter.schema';
import { newsletterResolvers } from '@modules/crm/newsletter/newsletter.resolver';
import { contactTypeDefs } from '@modules/crm/contact/contact.schema';
import { contactResolvers } from '@modules/crm/contact/contact.resolver';
import { analyticsTypeDefs } from '@modules/platform/analytics/analytics.schema';
import { analyticsResolvers } from '@modules/platform/analytics/analytics.resolver';
import { podPlanTypeDefs } from '@modules/pods/pod-plan/pod-plan.schema';
import { podPlanResolvers } from '@modules/pods/pod-plan/pod-plan.resolver';
import { podDraftTypeDefs } from '@modules/pods/pod-draft/pod-draft.schema';
import { podDraftResolvers } from '@modules/pods/pod-draft/pod-draft.resolver';
import { searchTypeDefs } from '@modules/pods/search/search.schema';
import { searchResolvers } from '@modules/pods/search/search.resolver';
import { whatsappTypeDefs } from '@modules/access/auth-whatsapp/auth-whatsapp.schema';
import { whatsappResolvers } from '@modules/access/auth-whatsapp/auth-whatsapp.resolver';
import { inventoryTypeDefs } from '@modules/venues/inventory/inventory.schema';
import { inventoryResolvers } from '@modules/venues/inventory/inventory.resolver';
import { partnerDashboardTypeDefs } from '@modules/venues/partnerDashboard/partnerDashboard.schema';
import { partnerDashboardResolvers } from '@modules/venues/partnerDashboard/partnerDashboard.resolver';
import { websiteContentTypeDefs } from '@modules/content/websiteContent/websiteContent.schema';
import { websiteContentResolvers } from '@modules/content/websiteContent/websiteContent.resolver';
import { jobApplicationTypeDefs } from '@modules/content/jobApplication/jobApplication.schema';
import { jobApplicationResolvers } from '@modules/content/jobApplication/jobApplication.resolver';
import { websiteNavTypeDefs } from '@modules/content/websiteNav/websiteNav.schema';
import { websiteNavResolvers } from '@modules/content/websiteNav/websiteNav.resolver';
import { marketingTypeDefs } from '@modules/crm/marketing/marketing.schema';
import { marketingResolvers } from '@modules/crm/marketing/marketing.resolver';
import { crmTypeDefs } from '@modules/crm/crm/crm.schema';
import { crmResolvers } from '@modules/crm/crm/crm.resolver';
import { commsProviderTypeDefs } from '@modules/crm/commsProvider/commsProvider.schema';
import { commsProviderResolvers } from '@modules/crm/commsProvider/commsProvider.resolver';
import { communicationLogTypeDefs } from '@modules/crm/communicationLog/communicationLog.schema';
import { communicationLogResolvers } from '@modules/crm/communicationLog/communicationLog.resolver';
import { callPromptTypeDefs } from '@modules/crm/callPrompt/callPrompt.schema';
import { callPromptResolvers } from '@modules/crm/callPrompt/callPrompt.resolver';
import { serviceOfferedTypeDefs } from '@modules/crm/serviceOffered/serviceOffered.schema';
import { serviceOfferedResolvers } from '@modules/crm/serviceOffered/serviceOffered.resolver';
import { managedOptionTypeDefs } from '@modules/crm/managedOption/managedOption.schema';
import { managedOptionResolvers } from '@modules/crm/managedOption/managedOption.resolver';
import { websitePageTypeDefs } from '@modules/crm/websitePage/websitePage.schema';
import { websitePageResolvers } from '@modules/crm/websitePage/websitePage.resolver';
import { crmEmailTemplateTypeDefs } from '@modules/crm/emailTemplate/crmEmailTemplate.schema';
import { crmEmailTemplateResolvers } from '@modules/crm/emailTemplate/crmEmailTemplate.resolver';
import { reminderTypeDefs } from '@modules/crm/reminder/reminder.schema';
import { reminderResolvers } from '@modules/crm/reminder/reminder.resolver';
import { waLeadsTypeDefs } from '@modules/crm/whatsapp/whatsapp.schema';
import { waLeadsResolvers } from '@modules/crm/whatsapp/whatsapp.resolver';
import { surveyTypeDefs } from '@modules/survey/survey.schema';
import { surveyResolvers } from '@modules/survey/survey.resolver';
import { meetingTypeDefs } from '@modules/survey/meeting.schema';
import { meetingResolvers } from '@modules/survey/meeting.resolver';
import { leadSurveyTypeDefs } from '@modules/survey/leadSurvey.schema';
import { leadSurveyResolvers } from '@modules/survey/leadSurvey.resolver';
import { bouncerTypeDefs } from '@modules/support/bouncer/bouncer.schema';
import { bouncerResolvers } from '@modules/support/bouncer/bouncer.resolver';
import { venueSlotTypeDefs } from '@modules/venues/venueSlot/venueSlot.schema';
import { venueSlotResolvers } from '@modules/venues/venueSlot/venueSlot.resolver';
import { slotTemplateTypeDefs } from '@modules/venues/slotTemplate/slotTemplate.schema';
import { slotTemplateResolvers } from '@modules/venues/slotTemplate/slotTemplate.resolver';
import { ecommBrandTypeDefs } from '@modules/venues/ecommBrand/ecommBrand.schema';
import { ecommBrandResolvers } from '@modules/venues/ecommBrand/ecommBrand.resolver';
import { accountHealthTypeDefs } from '@modules/access/accountHealth/accountHealth.schema';
import { accountHealthResolvers } from '@modules/access/accountHealth/accountHealth.resolver';
import { ticketTypeDefs } from '@modules/support/ticket/ticket.schema';
import { ticketResolvers } from '@modules/support/ticket/ticket.resolver';
import { supportChatTypeDefs } from '@modules/support/supportChat/supportChat.schema';
import { supportChatResolvers } from '@modules/support/supportChat/supportChat.resolver';
import { legalDocumentTypeDefs } from '@modules/content/legalDocument/legalDocument.schema';
import { legalDocumentResolvers } from '@modules/content/legalDocument/legalDocument.resolver';
import { envEntryTypeDefs } from '@modules/platform/envEntry/envEntry.schema';
import { envEntryResolvers } from '@modules/platform/envEntry/envEntry.resolver';
import { portalModeTypeDefs } from '@modules/platform/portalMode/portalMode.schema';
import { portalModeResolvers } from '@modules/platform/portalMode/portalMode.resolver';
import { techTypeDefs } from '@modules/platform/tech/tech.schema';
import { techResolvers } from '@modules/platform/tech/tech.resolver';
import { challengeTypeDefs } from '@modules/engagement/challenge/challenge.schema';
import { challengeResolvers } from '@modules/engagement/challenge/challenge.resolver';
import { approvalTypeDefs } from '@modules/approval/approval.schema';
import { approvalResolvers } from '@modules/approval/approval.resolver';
import { moderationTypeDefs } from '@modules/moderation/moderation.schema';
import { moderationResolvers } from '@modules/moderation/moderation.resolver';
import { hostRequestTypeDefs } from '@modules/crm/hostRequest/hostRequest.schema';
import { hostRequestResolvers } from '@modules/crm/hostRequest/hostRequest.resolver';
import { apiKeyTypeDefs } from '@modules/platform/apiKey/apiKey.schema';
import { apiKeyResolvers } from '@modules/platform/apiKey/apiKey.resolver';
import { tableQueryTypeDefs } from './table-query.schema';

const rootTypeDefs = gql`
  type Query {
    _ping: String!
  }
  type Mutation {
    _noop: Boolean
  }
`;

const rootResolvers = {
  Query: { _ping: () => 'pong' },
  Mutation: { _noop: () => true },
};

export const typeDefs = [rootTypeDefs, tableQueryTypeDefs, userTypeDefs, verificationTypeDefs, rbacTypeDefs, settingsTypeDefs, categoryTypeDefs, locationTypeDefs, clubTypeDefs, podTypeDefs, clubAdminTypeDefs, notificationTypeDefs, referralTypeDefs, interviewTypeDefs, faqTypeDefs, financeTypeDefs, paymentTypeDefs, couponTypeDefs, expenseTypeDefs, walletTypeDefs, founderTypeDefs, eventTicketTypeDefs, aiTypeDefs, aiPromptTypeDefs, postTypeDefs, policyTypeDefs, podIdeaTypeDefs, uploadTypeDefs, emailTemplateTypeDefs, podMemberTypeDefs, badgeTypeDefs, venueTypeDefs, hostTypeDefs, chatTypeDefs, newsletterTypeDefs, contactTypeDefs, analyticsTypeDefs, podPlanTypeDefs, podDraftTypeDefs, searchTypeDefs, whatsappTypeDefs, inventoryTypeDefs, partnerDashboardTypeDefs, websiteContentTypeDefs, jobApplicationTypeDefs, websiteNavTypeDefs, marketingTypeDefs, crmTypeDefs, commsProviderTypeDefs, communicationLogTypeDefs, callPromptTypeDefs, serviceOfferedTypeDefs, managedOptionTypeDefs, websitePageTypeDefs, crmEmailTemplateTypeDefs, reminderTypeDefs, waLeadsTypeDefs, surveyTypeDefs, meetingTypeDefs, leadSurveyTypeDefs, bouncerTypeDefs, venueSlotTypeDefs, slotTemplateTypeDefs, accountHealthTypeDefs, ticketTypeDefs, supportChatTypeDefs, legalDocumentTypeDefs, envEntryTypeDefs, portalModeTypeDefs, techTypeDefs, challengeTypeDefs, ecommBrandTypeDefs, approvalTypeDefs, moderationTypeDefs, hostRequestTypeDefs, productOrderTypeDefs, brandPickupLocationTypeDefs, apiKeyTypeDefs];

export const resolvers = [rootResolvers, userResolvers, verificationResolvers, rbacResolvers, settingsResolvers, categoryResolvers, locationResolvers, clubResolvers, podResolvers, clubAdminResolvers, notificationResolvers, referralResolvers, interviewResolvers, faqResolvers, financeResolvers, paymentResolvers, couponResolvers, expenseResolvers, walletResolvers, founderResolvers, eventTicketResolvers, aiResolvers, aiPromptResolvers, postResolvers, policyResolvers, podIdeaResolvers, uploadResolvers, emailTemplateResolvers, podMemberResolvers, badgeResolvers, venueResolvers, hostResolvers, chatResolvers, newsletterResolvers, contactResolvers, analyticsResolvers, podPlanResolvers, podDraftResolvers, searchResolvers, whatsappResolvers, inventoryResolvers, partnerDashboardResolvers, websiteContentResolvers, jobApplicationResolvers, websiteNavResolvers, marketingResolvers, crmResolvers, commsProviderResolvers, communicationLogResolvers, callPromptResolvers, serviceOfferedResolvers, managedOptionResolvers, websitePageResolvers, crmEmailTemplateResolvers, reminderResolvers, waLeadsResolvers, surveyResolvers, meetingResolvers, leadSurveyResolvers, bouncerResolvers, venueSlotResolvers, slotTemplateResolvers, accountHealthResolvers, ticketResolvers, supportChatResolvers, legalDocumentResolvers, envEntryResolvers, portalModeResolvers, techResolvers, challengeResolvers, ecommBrandResolvers, approvalResolvers, moderationResolvers, hostRequestResolvers, productOrderResolvers, brandPickupLocationResolvers, apiKeyResolvers];
