import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, screen, waitFor, within } from '@testing-library/react';
import { formatMjml } from '@duncit/utils';
import { AI_MJML } from '@/api/emailTemplates.gql';
import { insertMjmlImage } from '@/pages/email-templates/insertMjmlImage';
import { PREVIEW_WAIT, renderEditor, renderMock, templateMock, venueTemplate } from './editorHarness';

vi.mock('@monaco-editor/react', () => ({
  default: ({ value, onChange }: Readonly<{ value: string; onChange: (next: string | undefined) => void }>) => (
    <textarea aria-label="MJML editor" value={value} onChange={(e) => onChange(e.target.value)} />
  ),
}));

const writeText = vi.fn(() => Promise.resolve());

beforeEach(() => {
  Object.defineProperty(globalThis.navigator, 'clipboard', { configurable: true, value: { writeText } });
});

const editor = () => screen.getByLabelText('MJML editor');

describe('Email template editor — source pane', () => {
  it('tidies typed MJML and re-renders the preview for it', async () => {
    renderEditor([templateMock(venueTemplate), renderMock({ html: '<p>Tidy</p>' })]);
    const messy = '<mjml> <mj-body>  <mj-section><mj-column> <mj-text>Hi</mj-text> </mj-column></mj-section> </mj-body> </mjml>';

    fireEvent.change(await screen.findByLabelText('MJML editor'), { target: { value: messy } });
    fireEvent.click(screen.getByRole('button', { name: 'Format & tidy' }));

    expect(editor()).toHaveValue(formatMjml(messy));
    expect(screen.getByText('Unsaved changes')).toBeInTheDocument();
    await waitFor(() => expect(screen.getByTitle('preview')).toHaveAttribute('srcdoc', '<p>Tidy</p>'), PREVIEW_WAIT);
  });

  it('inserts a library image into the source', async () => {
    renderEditor([templateMock(venueTemplate), renderMock({})]);

    fireEvent.click(await screen.findByRole('button', { name: 'Image library' }));
    const dialog = within(await screen.findByRole('dialog', { name: /Image library/ }));
    expect(dialog.getByRole('img', { name: 'Hero' })).toHaveAttribute('src', 'https://cdn.duncit.com/hero.png');

    fireEvent.click(dialog.getByRole('button', { name: 'Insert <mj-image>' }));
    expect(editor()).toHaveValue(insertMjmlImage(venueTemplate.mjml, 'https://cdn.duncit.com/hero.png'));

    fireEvent.click(dialog.getByRole('button', { name: 'Close' }));
    await waitFor(() => expect(screen.queryByRole('dialog', { name: /Image library/ })).toBeNull());
  });

  it('applies MJML generated by AI from a prompt', async () => {
    const generated = '<mjml><mj-body><mj-text>Diwali offer</mj-text></mj-body></mjml>';
    renderEditor([
      templateMock(venueTemplate),
      renderMock({}),
      {
        request: { query: AI_MJML, variables: { input: { prompt: 'A Diwali offer', current_mjml: venueTemplate.mjml } } },
        result: { data: { aiCreateOrUpdateMjml: generated } },
      },
    ]);

    fireEvent.click(await screen.findByRole('button', { name: 'Create / update with AI' }));
    const popover = within(await screen.findByRole('dialog', { name: 'Create / update MJML with AI' }));
    fireEvent.change(popover.getByLabelText('Prompt'), { target: { value: '  A Diwali offer ' } });
    fireEvent.click(popover.getByRole('button', { name: 'Apply' }));

    await waitFor(() => expect(editor()).toHaveValue(generated));
  });

  it('removes an attachment from the template', async () => {
    renderEditor([templateMock(venueTemplate), renderMock({})]);

    expect(await screen.findByRole('link', { name: 'Rate card' })).toHaveAttribute('href', 'https://cdn.duncit.com/rate-card.pdf');
    fireEvent.click(within(screen.getByRole('link', { name: 'Rate card' }).closest('.MuiChip-root') as HTMLElement).getByTestId('CancelIcon'));

    expect(screen.queryByRole('link', { name: 'Rate card' })).toBeNull();
    expect(screen.getByText('Unsaved changes')).toBeInTheDocument();
  });
});

describe('Email template editor — variables pane', () => {
  it('syncs detected placeholders into the declared variables and edits them', async () => {
    renderEditor([templateMock(venueTemplate), renderMock({ detected: ['venue_name', 'city', 'coupon_code'] })]);

    fireEvent.click(await screen.findByRole('tab', { name: 'Variables' }));
    await waitFor(() => expect(screen.getByRole('button', { name: 'Sync all' })).toBeEnabled(), PREVIEW_WAIT);

    fireEvent.click(screen.getByRole('button', { name: 'Sync all' }));
    expect(screen.getByLabelText('city')).toBeInTheDocument();
    expect(screen.getByLabelText('coupon_code')).toBeInTheDocument();
    expect(screen.getAllByLabelText('Slug')).toHaveLength(3);

    // Deselecting a declared chip removes it; selecting it again adds it back.
    const cityChip = () =>
      screen.getAllByTestId('crm-template-variable-chip').find((chip) => chip.textContent?.endsWith('· city')) as HTMLElement;
    fireEvent.click(cityChip());
    expect(screen.queryByLabelText('city')).toBeNull();
    fireEvent.click(cityChip());
    expect(screen.getByLabelText('city')).toBeInTheDocument();
  });
});
