/**
 * GENERATED by `node scripts/generate-demo-registry.mjs` — do not edit.
 *
 * Every package's demo module, and the demo file's own source. Both are lazy:
 * a reader who opens one package downloads that package's demo chunk and
 * nothing else, which is what keeps a 48-package catalogue cheap to browse.
 */
import type { PackageDemoModule } from './types';

type DemoLoader = () => Promise<{ default: PackageDemoModule }>;
type SourceLoader = () => Promise<{ default: string }>;

const DEMOS: Record<string, DemoLoader> = {
  'ad-request-form': () => import('./demos/ad-request-form'),
  'ai-monitoring': () => import('./demos/ai-monitoring'),
  'ai-prompts': () => import('./demos/ai-prompts'),
  'app-settings': () => import('./demos/app-settings'),
  'auth-tokens': () => import('./demos/auth-tokens'),
  'auto-pods': () => import('./demos/auto-pods'),
  'availability-calendar': () => import('./demos/availability-calendar'),
  'brand': () => import('./demos/brand'),
  'breadcrumb': () => import('./demos/breadcrumb'),
  'buttons': () => import('./demos/buttons'),
  'buttons-native': () => import('./demos/buttons-native'),
  'captcha': () => import('./demos/captcha'),
  'category': () => import('./demos/category'),
  'club-form': () => import('./demos/club-form'),
  'communication': () => import('./demos/communication'),
  'coupons': () => import('./demos/coupons'),
  'dashboard': () => import('./demos/dashboard'),
  'datetime': () => import('./demos/datetime'),
  'dialogs': () => import('./demos/dialogs'),
  'dialogs-native': () => import('./demos/dialogs-native'),
  'docs-demos': () => import('./demos/docs-demos'),
  'earn': () => import('./demos/earn'),
  'errors': () => import('./demos/errors'),
  'fallback-icons': () => import('./demos/fallback-icons'),
  'forms': () => import('./demos/forms'),
  'geo': () => import('./demos/geo'),
  'gql-types': () => import('./demos/gql-types'),
  'host-pod-actions': () => import('./demos/host-pod-actions'),
  'i18n': () => import('./demos/i18n'),
  'location': () => import('./demos/location'),
  'logs': () => import('./demos/logs'),
  'media-picker': () => import('./demos/media-picker'),
  'onboarding': () => import('./demos/onboarding'),
  'pod-details': () => import('./demos/pod-details'),
  'pod-form': () => import('./demos/pod-form'),
  'pod-product-picker': () => import('./demos/pod-product-picker'),
  'portal-pod-form': () => import('./demos/portal-pod-form'),
  'regex': () => import('./demos/regex'),
  'rich-text': () => import('./demos/rich-text'),
  'shell': () => import('./demos/shell'),
  'slack': () => import('./demos/slack'),
  'slots': () => import('./demos/slots'),
  'table': () => import('./demos/table'),
  'tabs': () => import('./demos/tabs'),
  'theme': () => import('./demos/theme'),
  'tours': () => import('./demos/tours'),
  'ui': () => import('./demos/ui'),
  'user-context': () => import('./demos/user-context'),
  'user-core': () => import('./demos/user-core'),
  'utils': () => import('./demos/utils'),
  'verification': () => import('./demos/verification'),
  'virtual-scroll': () => import('./demos/virtual-scroll'),
};

/**
 * The demo file's own text, imported with `?raw`.
 *
 * The source shown beside a demo is THE FILE THAT JUST RAN, not a copy of it
 * written into a string — which is the only way a snippet cannot drift from the
 * component it claims to produce.
 */
const SOURCES: Record<string, SourceLoader> = {
  'ad-request-form': () => import('./demos/ad-request-form.tsx?raw'),
  'ai-monitoring': () => import('./demos/ai-monitoring.tsx?raw'),
  'ai-prompts': () => import('./demos/ai-prompts.tsx?raw'),
  'app-settings': () => import('./demos/app-settings.tsx?raw'),
  'auth-tokens': () => import('./demos/auth-tokens.tsx?raw'),
  'auto-pods': () => import('./demos/auto-pods.tsx?raw'),
  'availability-calendar': () => import('./demos/availability-calendar.tsx?raw'),
  'brand': () => import('./demos/brand.tsx?raw'),
  'breadcrumb': () => import('./demos/breadcrumb.tsx?raw'),
  'buttons': () => import('./demos/buttons.tsx?raw'),
  'buttons-native': () => import('./demos/buttons-native.tsx?raw'),
  'captcha': () => import('./demos/captcha.tsx?raw'),
  'category': () => import('./demos/category.tsx?raw'),
  'club-form': () => import('./demos/club-form.tsx?raw'),
  'communication': () => import('./demos/communication.tsx?raw'),
  'coupons': () => import('./demos/coupons.tsx?raw'),
  'dashboard': () => import('./demos/dashboard.tsx?raw'),
  'datetime': () => import('./demos/datetime.tsx?raw'),
  'dialogs': () => import('./demos/dialogs.tsx?raw'),
  'dialogs-native': () => import('./demos/dialogs-native.tsx?raw'),
  'docs-demos': () => import('./demos/docs-demos.tsx?raw'),
  'earn': () => import('./demos/earn.tsx?raw'),
  'errors': () => import('./demos/errors.tsx?raw'),
  'fallback-icons': () => import('./demos/fallback-icons.tsx?raw'),
  'forms': () => import('./demos/forms.tsx?raw'),
  'geo': () => import('./demos/geo.tsx?raw'),
  'gql-types': () => import('./demos/gql-types.tsx?raw'),
  'host-pod-actions': () => import('./demos/host-pod-actions.tsx?raw'),
  'i18n': () => import('./demos/i18n.tsx?raw'),
  'location': () => import('./demos/location.tsx?raw'),
  'logs': () => import('./demos/logs.tsx?raw'),
  'media-picker': () => import('./demos/media-picker.tsx?raw'),
  'onboarding': () => import('./demos/onboarding.tsx?raw'),
  'pod-details': () => import('./demos/pod-details.tsx?raw'),
  'pod-form': () => import('./demos/pod-form.tsx?raw'),
  'pod-product-picker': () => import('./demos/pod-product-picker.tsx?raw'),
  'portal-pod-form': () => import('./demos/portal-pod-form.tsx?raw'),
  'regex': () => import('./demos/regex.tsx?raw'),
  'rich-text': () => import('./demos/rich-text.tsx?raw'),
  'shell': () => import('./demos/shell.tsx?raw'),
  'slack': () => import('./demos/slack.tsx?raw'),
  'slots': () => import('./demos/slots.tsx?raw'),
  'table': () => import('./demos/table.tsx?raw'),
  'tabs': () => import('./demos/tabs.tsx?raw'),
  'theme': () => import('./demos/theme.tsx?raw'),
  'tours': () => import('./demos/tours.tsx?raw'),
  'ui': () => import('./demos/ui.tsx?raw'),
  'user-context': () => import('./demos/user-context.tsx?raw'),
  'user-core': () => import('./demos/user-core.tsx?raw'),
  'utils': () => import('./demos/utils.tsx?raw'),
  'verification': () => import('./demos/verification.tsx?raw'),
  'virtual-scroll': () => import('./demos/virtual-scroll.tsx?raw'),
};

/** Every package that ships a demo, alphabetically. */
export const DEMO_SLUGS: string[] = Object.keys(DEMOS).sort((a, b) => a.localeCompare(b));

/** One package's demos, or null when it ships none. */
export async function loadPackageDemos(slug: string): Promise<PackageDemoModule | null> {
  const load = DEMOS[slug];
  if (!load) return null;
  return (await load()).default;
}

/** The raw text of one package's demo file, for the editor. */
export async function loadPackageDemoSource(slug: string): Promise<string> {
  const load = SOURCES[slug];
  if (!load) return '';
  return (await load()).default;
}
