import type { NavigationPage } from './askBot.catalog';

/**
 * Every page in every Duncit staff console, as the navigation bot knows them.
 *
 * Each row is read off that portal's own `appConfig.nav` and its route tree
 * (`portals/<name>/src/config/app-config.ts` + `src/App.tsx`), and the
 * description says what a person can actually DO on the page — that is the half
 * the bot answers with, so it is written from the page, never guessed.
 *
 * Adding a page to a portal means adding a row here in the same change,
 * otherwise the bot will tell people it does not exist.
 */

export const PORTAL_PAGES: readonly NavigationPage[] = [
  // ---- Admin (admin) --------------------------------------------------
  { surface: 'admin', path: '/hub', label: 'Hub',
    description: 'Pick one of six module tiles (Dashboard, User Management, Catalog, Community, Engagement, System) to jump into that workspace, and drag or resize the tiles to your own layout.' },
  { surface: 'admin', path: '/dashboard', label: 'Dashboard',
    description: 'See platform-wide summary tiles plus pods-by-super-category and clubs-by-super-category breakdowns, filtered by a super category, on a draggable widget grid.' },
  { surface: 'admin', path: '/users', label: 'All Users', group: 'User Management',
    description: 'Search and filter every user account, create a new user with a generated password and roles, and click a row to open that user\'s full detail page.' },
  { surface: 'admin', path: '/rbac/roles', label: 'Roles', group: 'User Management',
    description: 'Create, rename and delete portal access roles, and manage the list of super admins from the card above the table.' },
  { surface: 'admin', path: '/clubs', label: 'Clubs',
    description: 'Browse every club, create or edit one in the full club form (images, admins, verified and active flags, drafts), delete a club, or open its detail page.' },
  { surface: 'admin', path: '/venues', label: 'Venues',
    description: 'Read-only server-paged list of every registered venue — approvals and venue edits happen in the Onboarding portal, not here.' },
  { surface: 'admin', path: '/partners', label: 'Partners',
    description: 'List everyone holding a partner role (Host, Venue Partner, Product Seller, Club Admin), filter by partner type, and click through to their user details.' },
  { surface: 'admin', path: '/pods/dashboard', label: 'Dashboard', group: 'Pods',
    description: 'Review pod counts, seats, money, ratings, a creation trend chart and the best-rated / needs-attention / starting-next lists for a chosen reporting window.' },
  { surface: 'admin', path: '/pods', label: 'All Pods', group: 'Pods',
    description: 'Filter pods by club, toggle cancelled pods into view, create or fully edit a pod, quick-edit, delete, complete a pod (with release summary), open its AI activity trail, or view its detail page.' },
  { surface: 'admin', path: '/auto-pods', label: 'Auto Pods', group: 'Pods',
    description: 'Write a pod with no venue, host or club and watch its three enrolment ticks (Venue Enroll, Host Enroll, Club Admin Enroll) fill in as partners claim it; edit the template while it is still open, cancel it with a reason, or open the pod it materialized into.' },
  { surface: 'admin', path: '/pod-ideas', label: 'Pod Ideas', group: 'Pods',
    description: 'Review member-submitted pod ideas, open an idea\'s details and comments, mark its status, or delete it.' },
  { surface: 'admin', path: '/pod-plans', label: 'Pod Plans', group: 'Pods',
    description: 'Create, edit and delete the Free/Premium pod plan tiers shown in the mobile web app (visibility controlled by the pod_plans_section feature flag).' },
  { surface: 'admin', path: '/event-tickets', label: 'Event Tickets', group: 'Pods',
    description: 'Paste a scanned QR token to verify and check a ticket in, browse issued tickets, download a ticket PDF, and name companions when a multi-seat ticket is checked in.' },
  { surface: 'admin', path: '/pod-settings', label: 'Pod Settings', group: 'Pods',
    description: 'Set the draft-pod retention period in days, the maximum backout attempts per user per pod, and the account-health penalty a venue pays when it cancels a booked pod.' },
  { surface: 'admin', path: '/pod-monitoring', label: 'Pod Monitoring (AI)', group: 'Pods',
    description: 'Browse the AI risk-scored audit trail of every pod edit, status change and critical action across all surfaces, and open a row for the full change detail.' },
  { surface: 'admin', path: '/membership/plans', label: 'Plans', group: 'Membership',
    description: 'Edit the membership catalogue in two tabs — the tiers themselves and the comparison rows that describe them — for the (currently inert) membership screens in the apps.' },
  { surface: 'admin', path: '/membership/subscribers', label: 'Subscribers', group: 'Membership',
    description: 'Read-only list of members who tapped "Notify me" on the Membership screen, searchable by email or name.' },
  { surface: 'admin', path: '/categories', label: 'Categories', group: 'Catalog',
    description: 'Drill through Super Categories, categories and sub-categories in three columns to create, edit, reorder or delete them, plus configure the All-Vibe icon and the Vibe heading.' },
  { surface: 'admin', path: '/locations', label: 'Locations', group: 'Catalog',
    description: 'Create, edit and delete cities/locations along with their zones (name and pincode), country/state details, image and active state.' },
  { surface: 'admin', path: '/faqs', label: 'FAQs', group: 'Engagement',
    description: 'Create, edit, reorder and delete the app-audience FAQs, optionally scoped to a super category.' },
  { surface: 'admin', path: '/partners/faqs', label: 'Partner FAQs', group: 'Engagement',
    description: 'Create, edit and delete the FAQs shown to partners in the partner-facing surfaces.' },
  { surface: 'admin', path: '/badges', label: 'Badges', group: 'Engagement',
    description: 'Create, edit and delete achievement badges — title, image, condition type and threshold — where deleting also revokes the badge from all users.' },
  { surface: 'admin', path: '/something-for-you', label: 'Something for you', group: 'Engagement',
    description: 'Add, edit, reorder and delete the promo cards in the sideways-scrolling row at the bottom of Home on both mWeb and the native app, each with an image, bottom text and a link action.' },
  { surface: 'admin', path: '/approvals', label: 'Approvals',
    description: 'Filter approval requests coming in from across the portals by status and approve or deny each one from a review dialog with optional notes.' },
  { surface: 'admin', path: '/portal-access', label: 'Portal Access',
    description: 'Work the Jump-to-Portal request inbox — see who asked for which console and when, filter by status, and approve (granting the role and emailing them) or deny.' },
  { surface: 'admin', path: '/upload-settings/portals', label: 'Portals Upload Setting', group: 'Upload Settings',
    description: 'Configure max upload sizes, allowed formats, image crop resolution presets, compression and AI image monitoring for every MUI portal.' },
  { surface: 'admin', path: '/upload-settings/mobile', label: 'Mobile App', group: 'Upload Settings',
    description: 'Configure max upload sizes, allowed formats, crop presets, compression and AI image monitoring for the native app (pods, reels, statuses, avatars).' },
  { surface: 'admin', path: '/upload-settings/mweb', label: 'mWeb Upload Setting', group: 'Upload Settings',
    description: 'Configure max upload sizes, allowed formats, crop presets, compression and AI image monitoring for the mWeb PWA (pods, reels, statuses, avatars).' },
  { surface: 'admin', path: '/localization/locales', label: 'Locales', group: 'Localization',
    description: 'Add, edit and remove the languages/country locales the platform renders in, including which one is default, RTL and active.' },
  { surface: 'admin', path: '/localization/translations', label: 'Translations', group: 'Localization',
    description: 'Browse translation namespaces, drill into one namespace\'s keys to add or edit each locale\'s copy, and press "Import app keys" to seed every shipped key.' },
  { surface: 'admin', path: '/branding', label: 'Branding', group: 'System',
    description: 'Edit the platform identity (app name, logo, primary colour, support contacts), per-platform favicon/logo/splash assets, website logos and store links, date-windowed occasional icons, and the Google font per platform.' },
  { surface: 'admin', path: '/settings', label: 'Settings', group: 'System',
    description: 'Toggle dark/light mode, set the platform-wide date and time display formats, choose the time zone and time source (with a live clock preview), and set the minimum signup age.' },
  { surface: 'admin', path: '/portal-app-settings', label: 'Portal App Setting', group: 'System',
    description: 'Toggle, per registered portal, whether its header offers the "Chat with a coworker" and Apps buttons.' },
  { surface: 'admin', path: '/profile', label: 'Profile',
    description: 'View the signed-in account\'s identity, access roles and linked Google account, edit your name, change your language, and sign out.' },

  // ---- Tech (tech) ----------------------------------------------------
  { surface: 'tech', path: '/', label: 'Environment Variables',
    description: 'Create, edit, delete and live-test named credential entries per category (email/SMTP, ImageKit, Google Maps, Google OAuth, Pexels, AI, calling, Slack, AiSensy), mark one as default, import/export them as JSON, and on the Portal Mapping tab assign which entries each portal consumes.' },
  { surface: 'tech', path: '/portal-modes', label: 'Maintenance',
    description: 'Switch any portal, website or app between Live, Maintenance and Development so visitors are blocked with the matching page until it is set back to Live.' },
  { surface: 'tech', path: '/feature-flags', label: 'Feature Flags',
    description: 'Create, rename, toggle and delete feature flags that switch product features on or off without a deploy, and carry the whole set to another environment via JSON import/export.' },
  { surface: 'tech', path: '/authentication', label: 'Authentication',
    description: 'Set how long login sessions last by editing the JWT expiry value and unit, or switch tokens to never expire.' },
  { surface: 'tech', path: '/emails/dashboard', label: 'Dashboard', group: 'Emails',
    description: 'Review email delivery over a chosen date range — totals, the reasons sends never left (template off, missing address, provider refusal), which templates failed most and which recipients repeatedly fail.' },
  { surface: 'tech', path: '/emails/templates', label: 'Templates', group: 'Emails',
    description: 'Create, edit and delete MJML email templates by slug, validate and preview the rendered HTML with sample variables, attach header/footer fragments and send a live test email.' },
  { surface: 'tech', path: '/emails/fragments', label: 'Fragments', group: 'Emails',
    description: 'Edit, preview, activate, reset or add the header/footer fragment pairs that wrap each email category\'s body.' },
  { surface: 'tech', path: '/emails/logs', label: 'Logs', group: 'Emails',
    description: 'Search and filter every email send attempt including the ones that never left, open a row for the full variables and error detail, and bulk-delete logs (SUPER_ADMIN can wipe all).' },
  { surface: 'tech', path: '/mail-automation', label: 'Mail Automation', group: 'Emails',
    description: 'Connect and disconnect the Google mailboxes Duncit reads incoming mail from via OAuth, and see the redirect URI Google must have registered (the reply rules themselves live in the Support portal).' },
  { surface: 'tech', path: '/telemetry/dashboard', label: 'Dashboard', group: 'Telemetry',
    description: 'See platform log volume for a chosen range — total logs, error count, active bugs, sources, distribution by level/source and the most frequent open bugs alongside recent log rows.' },
  { surface: 'tech', path: '/telemetry/bugs', label: 'Bugs', group: 'Telemetry',
    description: 'Browse error logs rolled up into bugs by page and platform with occurrence counts, open one for its per-environment breakdown, and mark it resolved, ignored or reopened.' },
  { surface: 'tech', path: '/telemetry/logs-settings', label: 'Logs Settings', group: 'Telemetry',
    description: 'Turn SigNoz forwarding on or off, choose which log levels get persisted to the database, and set how many days logs are retained.' },
  { surface: 'tech', path: '/server/info', label: 'Info', group: 'Server',
    description: 'Read live host metrics for the machine running the API — CPU usage and cores, memory, disk, uptime, OS/distro plus SSH and SSL detail — and refresh them on demand.' },
  { surface: 'tech', path: '/server/docker', label: 'Docker', group: 'Server',
    description: 'List every Docker container on the host with its state, restart a container and watch its live logs stream in a dialog.' },
  { surface: 'tech', path: '/server/terminal', label: 'Terminal', group: 'Server',
    description: 'Run one-shot shell commands inside the API container from a web terminal and read stdout/stderr and exit codes (SUPER_ADMIN only; every command is audited).' },
  { surface: 'tech', path: '/server/data-clone', label: 'Data Clone', group: 'Server',
    description: 'Configure the source/target database connections and start a production-to-staging data clone, then watch its progress, excluded collections and completion without leaving the page.' },
  { surface: 'tech', path: '/slack', label: 'Slack',
    description: 'Use the connected Slack workspace as a chat client — pick a channel, read its message history and post a message — and check the bot\'s permissions when something fails.' },
  { surface: 'tech', path: '/app-builds/android', label: 'Android', group: 'App Builds',
    description: 'Track every CI Android build of the mobile app with live status polling, open a build for its full details and download link, trigger a new build, or delete a build and its stored artifact.' },
  { surface: 'tech', path: '/app-builds/ios', label: 'iOS', group: 'App Builds',
    description: 'Track every CI iOS build of the mobile app with live status polling, open a build for its details and artifact, start a new build, or delete a build and its stored file.' },
  { surface: 'tech', path: '/app-builds/settings', label: 'Settings', group: 'App Builds',
    description: 'Choose which Slack channels CI build announcements post to and manage the CI credential token used to trigger builds.' },
  { surface: 'tech', path: '/aisensy', label: 'AiSensy',
    description: 'Check whether the AiSensy WhatsApp API key is configured and send a live WhatsApp template campaign as a test with your own parameters.' },
  { surface: 'tech', path: '/package-docs', label: 'Package Documentation',
    description: 'Browse and search the documentation for every shared @duncit/* package, read straight from each package\'s own docs/index.mdx.' },
  { surface: 'tech', path: '/profile', label: 'Profile',
    description: 'View and edit your own account — name and profile photo, display language, assigned roles and linked Google account — and sign out.' },

  // ---- Finance (finance) ----------------------------------------------
  { surface: 'finance', path: '/', label: 'Dashboard',
    description: 'Read live finance KPI tiles — total collected (GMV), Duncit revenue, GST collected, pending payouts and completed payouts, each with its month-on-month change — on a dashboard grid you can rearrange and resize.' },
  { surface: 'finance', path: '/startup-dashboard', label: 'Startup Dashboard',
    description: 'Pick a date range and browse founder-level metric cards grouped by category, opening any metric\'s drawer to read how it is calculated or to edit the target/threshold settings behind it.' },
  { surface: 'finance', path: '/default-deductions', label: 'Default Deductions',
    description: 'Set the platform-wide percentage defaults with sliders — GST %, platform fee %, and the default host, venue, product, club-admin commission plus the backout deduction — and save them as the finance engine\'s defaults.' },
  { surface: 'finance', path: '/pod-finance', label: 'Pod Finance',
    description: 'Browse every pod that has payment-release activity, grouped per pod with its release count, requested total and PENDING/APPROVED/REJECTED status chips, then open a pod to see its settlement waterfall and host earnings.' },
  { surface: 'finance', path: '/cancellations', label: 'Dashboard', group: 'Cancel & Refunds',
    description: 'See KPI tiles for total pod cancellations split by host, venue and club admin plus the total refunded, over a searchable newest-first list of every cancellation you can open for detail.' },
  { surface: 'finance', path: '/backout-refunds', label: 'User Backout Refunds', group: 'Cancel & Refunds',
    description: 'Work the queue of attendee backout requests with their lifecycle status and process the refund (against the configured backout deduction %) once a backed-out spot has been filled.' },
  { surface: 'finance', path: '/cancellations/venue', label: 'Venue Cancel', group: 'Cancel & Refunds',
    description: 'List the pods that ended because the venue declined the booking and open a row for the decline reason and what the booking was worth (attendee refunds are zero since a venue can only decline before a pod goes live).' },
  { surface: 'finance', path: '/cancellations/host', label: 'Host Cancel', group: 'Cancel & Refunds',
    description: 'List the pods their host cancelled and open a row for the host\'s reason, the attendee refund status for each payment, and the venue\'s booked amount the cancellation cost.' },
  { surface: 'finance', path: '/payment-logs', label: 'Payment Logs',
    description: 'Search and filter every payment with live-polling totals (count, gross, fee, GST) that track your filter, issue a refund on a row, download its invoice PDF, and open a payment for the full audit of what it charged and created.' },
  { surface: 'finance', path: '/payment-release', label: 'Payment Release',
    description: 'Review the queue of venue billing and host payment-release requests and approve or reject each one, adjusting the released amount in the review form.' },
  { surface: 'finance', path: '/withdrawals', label: 'Withdrawal Payments', group: 'Withdrawal',
    description: 'Every pod money has been withdrawn against, showing which partners (host, venue owner, e-commerce brand, club admin) have requested so far and whether all of them have been paid. Filter by role and open a pod to review its requests.' },
  { surface: 'finance', path: '/withdrawals/:podId', label: 'Pod Withdrawal Requests', group: 'Withdrawal',
    description: 'The withdrawal requests raised against one pod: withdrawer name, method, role, date, amount and payout account. Open a request to read the full unmasked account details, then mark it Paid after transferring or reject it with a reason.' },
  { surface: 'finance', path: '/withdrawals/settings', label: 'Withdrawal Settings', group: 'Withdrawal',
    description: 'Set and save the minimum withdrawal amount separately for each withdrawer role (host, venue, club admin, brand).' },
  { surface: 'finance', path: '/invoices', label: 'Business Identity', group: 'Invoices',
    description: 'Edit the business identity printed on every invoice and ticket PDF — legal name, address, GSTIN, currency symbol, invoice prefix and label, support email/phone, footer note, terms and logo — with a live preview and a dummy-mode switch.' },
  { surface: 'finance', path: '/invoices/venue', label: 'Venue Invoice', group: 'Invoices',
    description: 'Edit the venue invoice template\'s label, terms, footer and note, which are applied to every venue invoice generated after saving.' },
  { surface: 'finance', path: '/invoices/host', label: 'Host Invoice', group: 'Invoices',
    description: 'Edit the host invoice template\'s label, terms, footer and note, applied to every host invoice generated after saving.' },
  { surface: 'finance', path: '/invoices/product', label: 'Product Invoice', group: 'Invoices',
    description: 'Edit the product invoice template\'s label, terms, footer and note, applied to every product/shop-order invoice generated after saving.' },
  { surface: 'finance', path: '/ledger', label: 'Duncit Expenses',
    description: 'Log and manage Duncit\'s own expenses — add a new expense in the drawer, filter and search the expense table, and watch the summary chips recompute against the same filters.' },
  { surface: 'finance', path: '/duncit-coin/dashboard', label: 'Dashboard', group: 'Duncit Coin',
    description: 'See Duncit Coin stat tiles (issued, redeemed, outstanding, wallet balances) with a drift warning when the ledger and wallet totals disagree, plus a monthly distribution chart over a selectable 6/12/24/36-month window.' },
  { surface: 'finance', path: '/duncit-coin/transactions', label: 'Transactions', group: 'Duncit Coin',
    description: 'Search and page the full coin ledger — which user earned or spent how many coins on which pod\'s order — and narrow it to a single pod with the pod picker.' },
  { surface: 'finance', path: '/duncit-coin/settings', label: 'Coin Settings', group: 'Duncit Coin',
    description: 'Set the rules that mint coins — pod-join earn %, shop earn % and coins per referral — and grant or deduct coins to a specific user as a one-off adjustment.' },
  { surface: 'finance', path: '/gift-cards/dashboard', label: 'Dashboard', group: 'Gift Cards',
    description: 'See gift card stat tiles — cards sold, value sold, value converted to coins, outstanding liability and expired breakage — over a monthly sold-vs-redeemed chart, and edit the sales policy (amount presets, min/max, validity months).' },
  { surface: 'finance', path: '/gift-cards/cards', label: 'Cards', group: 'Gift Cards',
    description: 'Browse every gift card ever sold — code, theme, amount, status, buyer, recipient, redeemer and expiry — with search and filters.' },
  { surface: 'finance', path: '/gift-cards/logs', label: 'Logs', group: 'Gift Cards',
    description: 'Search and page the gift card ledger — every card issued on a purchase and every conversion into Duncit Coins, with the acting user.' },
  { surface: 'finance', path: '/referrals', label: 'Referrals',
    description: 'Edit the referral share message template with a live preview of the link members will send, and browse the table of who referred whom (the coin payout itself is set in Duncit Coin > Settings).' },
  { surface: 'finance', path: '/payouts', label: 'Payout Cycles',
    description: 'Choose whether venue and host payouts run immediately or on a schedule, and when scheduled set the weekday and time-of-day the payout cycle fires.' },
  { surface: 'finance', path: '/calculators/pod-profit', label: 'Pod Profit', group: 'Calculators',
    description: 'Enter ticket price, spot count and venue/host commission percentages to model the venue payout, host payout and Duncit revenue for a hypothetical pod, mirroring the live finance engine.' },
  { surface: 'finance', path: '/profile', label: 'Profile',
    description: 'View and edit your own signed-in account — name, profile photo, email, roles, linked Google account and interface language — or sign out.' },

  // ---- Support (support) ----------------------------------------------
  { surface: 'support', path: '/', label: 'Dashboard',
    description: 'See live counts of active SOS alerts, pending callbacks, open tickets and open chats as clickable KPI tiles that jump straight to each queue, kept current over the support socket.' },
  { surface: 'support', path: '/sos', label: 'SOS Alerts',
    description: 'Monitor the live, socket-refreshed list of safety alerts users raised and open one to acknowledge or resolve it.' },
  { surface: 'support', path: '/callbacks', label: 'Callback Requests',
    description: 'Work the socket-refreshed list of users who asked to be called back and open a request to mark it contacted or close it.' },
  { surface: 'support', path: '/tickets', label: 'Tickets',
    description: 'Browse and search support tickets with a priority-first sort, raise a new ticket from the dialog, and open a ticket to read its thread and reply (email tickets reply from the connected mailbox).' },
  { surface: 'support', path: '/live-chat', label: 'Chat with Us',
    description: 'Run the live support inbox — filter sessions by status, search them, claim a chat, read the thread with typing indicators and read receipts, send messages with attachments, and create a user account from a chat.' },
  { surface: 'support', path: '/mail-automation', label: 'Mail Automation',
    description: 'Manage each connected support mailbox in a table, pause one, and configure its three-step rule (mailbox, ticket type, auto-reply message) plus review the recent threads it turned into tickets — connecting or disconnecting a mailbox is the Tech portal\'s job.' },
  { surface: 'support', path: '/reported-problems', label: 'Problems', group: 'Reported Problems',
    description: 'Browse and filter every problem submitted from the app\'s Report a Problem form — report ID, category, message, reporter and status — and open one for the full report.' },
  { surface: 'support', path: '/reported-problems/settings', label: 'Settings', group: 'Reported Problems',
    description: 'Control what the app\'s Report a Problem form offers — add or remove category chips, edit the message label, hint and minimum length, and toggle media attachments with a maximum count.' },
  { surface: 'support', path: '/profile', label: 'Profile',
    description: 'View and edit your own signed-in account — name, profile photo, email, roles, linked Google account and interface language — or sign out.' },

  // ---- CRM (crm) ------------------------------------------------------
  { surface: 'crm', path: '/', label: 'Dashboard',
    description: 'Read venue/host lead totals, conversion rate and unique-service count for a chosen date range, and study the pipeline-stage, priority-mix, super-category and services charts on a drag-and-resize widget grid.' },
  { surface: 'crm', path: '/venue-leads', label: 'Venue Leads', group: 'Leads',
    description: 'Browse, search, filter and sort every venue lead, create one, open it to view or edit, delete it, bulk-create leads with the Fill-with-AI dialog, import leads from Excel or export/download the Excel template.' },
  { surface: 'crm', path: '/venue-leads/new', label: 'New Venue Lead', group: 'Leads',
    description: 'Fill the venue lead form (contact, location, capacity, services offered, amenities, dynamic fields) and save it as a new venue lead, optionally starting from an AI-prefilled draft.' },
  { surface: 'crm', path: '/venue-leads/services', label: 'Manage Venue Services', group: 'Leads',
    description: 'Add, rename, reorder, activate/deactivate and delete the entries in the Services Offered dropdown that the Venue Lead form uses.' },
  { surface: 'crm', path: '/host-leads', label: 'Host Leads', group: 'Leads',
    description: 'Browse, search, filter and sort host and organizer leads, create one, view/edit/delete it, bulk-create with Fill-with-AI, and import or export host leads as Excel.' },
  { surface: 'crm', path: '/host-leads/new', label: 'New Host Lead', group: 'Leads',
    description: 'Fill the host lead form (contact, category, services, dynamic fields) and save it as a new host lead, optionally from an AI-prefilled draft.' },
  { surface: 'crm', path: '/host-leads/services', label: 'Manage Host Services', group: 'Leads',
    description: 'Add, rename, reorder, activate/deactivate and delete the entries in the Services Offered dropdown that the Host Lead form uses.' },
  { surface: 'crm', path: '/ecomm-leads', label: 'Ecomm Leads', group: 'Leads',
    description: 'Browse and qualify product-seller leads captured from the app onboarding gate or entered manually, and create, view, edit or delete them.' },
  { surface: 'crm', path: '/ecomm-leads/new', label: 'New Ecomm Lead', group: 'Leads',
    description: 'Fill the ecomm lead form (seller details, category, services, dynamic fields) and save it as a new product-seller lead.' },
  { surface: 'crm', path: '/ecomm-leads/services', label: 'Manage Ecomm Services', group: 'Leads',
    description: 'Add, rename, reorder, activate/deactivate and delete the entries in the Services Offered dropdown that the Ecomm Lead form uses.' },
  { surface: 'crm', path: '/user-leads', label: 'WhatsApp Leads', group: 'Leads > User Leads',
    description: 'Review WhatsApp-sourced user leads with a live stats bar and server-side searchable table, add or edit a lead, delete leads, import an xlsx/csv, export all leads to Excel, and run the clean-data pass.' },
  { surface: 'crm', path: '/tools/whatsapp', label: 'WhatsApp Lead Generator', group: 'Tools',
    description: 'Connect a WhatsApp account to the OpenWA gateway with an API key and QR scan, then browse its communities, groups and members and import them as user leads.' },
  { surface: 'crm', path: '/reminders', label: 'Reminders',
    description: 'View a full-page calendar of CRM reminders and lead follow-ups, colour-coded red for overdue, amber for due soon and green for later.' },
  { surface: 'crm', path: '/data/services-offered', label: 'Services Offered', group: 'Data',
    description: 'Curate the service titles per Super → Category → Sub taxonomy that the venue and host lead forms load dynamically, adding, editing or deleting entries and marking whether each applies to venues, hosts or both.' },
  { surface: 'crm', path: '/data/venues/amenities', label: 'Amenities management', group: 'Data > Venues',
    description: 'Add, edit, search and remove the venue amenity options (Parking, AC, Stage, Power Backup…) that appear as checkboxes on the Venue Lead form.' },
  { surface: 'crm', path: '/data/venues/event-suitability', label: 'Event Suitability management', group: 'Data > Venues',
    description: 'Add, edit, search and remove the event types (Birthday Party, Workshop, Corporate Meetup…) that drive the suitability picker on the Venue Lead form.' },
  { surface: 'crm', path: '/email-templates', label: 'Templates', group: 'Email Templates',
    description: 'List the CRM-owned MJML email templates with their variables, create a new template, open one to edit its source and preview, or delete it.' },
  { surface: 'crm', path: '/call-prompts', label: 'Static Content', group: 'AI Call Prompts',
    description: 'Create, edit and delete the reusable context blocks the AI agent speaks from during an AI Call.' },
  { surface: 'crm', path: '/settings/dynamic-fields', label: 'Dynamic Fields', group: 'Settings',
    description: 'Define the custom fields shown on venue and host lead forms — label, type, options, required and active state — and drag rows to reorder them.' },
  { surface: 'crm', path: '/profile', label: 'Profile',
    description: 'View the signed-in account\'s name, email, access roles and linked Google account, edit the name, change interface language, and sign out.' },

  // ---- Ads (ads) ------------------------------------------------------
  { surface: 'ads', path: '/', label: 'Dashboard',
    description: 'See your advertiser KPIs (total, live and pending ads), a banner naming the next ad that goes live and when, and the most recent ad requests — or an empty state that starts your first ad.' },
  { surface: 'ads', path: '/ads', label: 'My Ads', group: 'Create Ads',
    description: 'Track every ad request in a searchable, filterable table showing trace ID, title, placement, media type, start date, duration, estimated cost and review status, and open a row for its full detail.' },
  { surface: 'ads', path: '/ads/new', label: 'Create Ad', group: 'Create Ads',
    description: 'Submit a new ad request — title, placement, media, start date and duration — while a sticky estimate card quotes the cost live before you send it for Marketing review.' },
  { surface: 'ads', path: '/profile', label: 'Profile',
    description: 'View the signed-in account\'s name, email, access roles and linked Google account, edit the name, change interface language, and sign out.' },

  // ---- Marketing (marketing) ------------------------------------------
  { surface: 'marketing', path: '/', label: 'Dashboard',
    description: 'Read last-N-days link clicks, revenue from links, emails delivered and live ads as clickable KPI tiles, then drill into a clicks-over-time chart, top links, recent campaign performance, click sources, countries and a what-is-set-up summary on a draggable widget grid.' },
  { surface: 'marketing', path: '/audience', label: 'Target Audience',
    description: 'Browse the saved audience lists — each stores its filters so membership stays current — open one to inspect its members, delete a list, or start a new one.' },
  { surface: 'marketing', path: '/audience/new', label: 'Create list',
    description: 'Work through a two-step wizard: filter down to the people you want with a live match count, then name the list, describe it and pick its owner to save it.' },
  { surface: 'marketing', path: '/campaigns/email', label: 'Email', group: 'Campaigns',
    description: 'Review every email campaign sent or scheduled, open one to see the exact email that went out plus its engagement, send a saved draft, or delete a campaign.' },
  { surface: 'marketing', path: '/campaigns/email/new', label: 'New campaign', group: 'Campaigns',
    description: 'Write the MJML email beside a live rendered preview with variable chips and unknown-variable warnings, pick the audience list, then send it immediately or schedule it.' },
  { surface: 'marketing', path: '/campaigns/whatsapp', label: 'WhatsApp', group: 'Campaigns',
    description: 'Send an approved AiSensy WhatsApp template to a Target Audience list, fire a test message, manage the campaign-name options, review past sends with their per-recipient results and retry or duplicate one, and browse the AiSensy Campaigns and Templates tabs.' },
  { surface: 'marketing', path: '/notifications', label: 'Notifications', group: 'Campaigns',
    description: 'Send a push and in-app notification to all users, a city or zone, an audience list, or specific users, and review or delete past sends with their delivered and failed counts.' },
  { surface: 'marketing', path: '/app-popups', label: 'App Popups', group: 'Campaigns',
    description: 'Create, edit, schedule, enable/disable and delete the full-screen image popup the app shows on open, targeting an audience list within a date window — each person sees it once.' },
  { surface: 'marketing', path: '/campaigns/mail-preferences', label: 'Mail Preferences', group: 'Campaigns',
    description: 'Read who has opted out of marketing email over a 7, 30, 90 or 365-day window — people opted out, opted out of everything, opt-outs and opt-ins — with per-category and per-source breakdowns and a searchable change log.' },
  { surface: 'marketing', path: '/short-links', label: 'Short Links',
    description: 'Create a duncit.com/<code> short link tagged with source and medium, browse every link with its click and conversion counts, open one for its full analytics, or delete it.' },
  { surface: 'marketing', path: '/coupons', label: 'Coupons',
    description: 'Create, edit and delete global discount codes and per-pod offer codes that apply at the payment step; the codes of a single pod are also managed from that pod in Admin.' },
  { surface: 'marketing', path: '/ads-approvals', label: 'Ads Approval', group: 'Ads',
    description: 'Filter ad requests submitted from the Ads portal by status and approve or reject each one with remarks — approval freezes the cost at the current pricing.' },
  { surface: 'marketing', path: '/live-ads', label: 'Live Ads', group: 'Ads',
    description: 'See every ad showing in the app right now, open a row for its full detail and creative, and stop an ad immediately or delete it along with its billing record.' },
  { surface: 'marketing', path: '/ads-settings', label: 'Ads Settings', group: 'Ads',
    description: 'Edit the per-day placement pricing and placement copy used to quote every ad request; approved ads keep the cost frozen at approval time.' },
  { surface: 'marketing', path: '/profile', label: 'Profile',
    description: 'View the signed-in account\'s name, email, access roles and linked Google account, edit the name, change interface language, and sign out.' },

  // ---- Website (website-app) ------------------------------------------
  { surface: 'website-app', path: '/', label: 'Dashboard',
    description: 'See live counts of career, newsroom and blog entries plus newsletter subscribers and new contact/FAQ submissions as draggable tiles, each linking to its section.' },
  { surface: 'website-app', path: '/careers', label: 'Career',
    description: 'Create, edit and delete the career and job posts published on duncit.com, setting title, slug, summary, body, image, CTA, publish state and sort order.' },
  { surface: 'website-app', path: '/newsroom', label: 'Newsroom',
    description: 'Create, edit and delete the newsroom and press entries published on duncit.com, setting title, slug, summary, body, image, CTA and publish state.' },
  { surface: 'website-app', path: '/blog', label: 'Blog',
    description: 'Create, edit and delete the blog articles published on duncit.com, setting title, slug, summary, body, category, image, CTA and publish state.' },
  { surface: 'website-app', path: '/newsletter', label: 'Newsletter Submission',
    description: 'Review every newsletter subscriber with total/active counts, filter by signup source and date, and see who has unsubscribed.' },
  { surface: 'website-app', path: '/contact-submissions', label: 'Contact Submission',
    description: 'Work the contact-form inbox — open a submission to read its full message and move its status as you handle it.' },
  { surface: 'website-app', path: '/faq-submissions', label: 'FAQ Submission',
    description: 'Triage questions visitors submitted, marking each one Converted once it becomes a published FAQ or Ignored if it will not be used.' },
  { surface: 'website-app', path: '/job-applications', label: 'Job Applications',
    description: 'Review applications sent from the careers page, open one for its full details and resume, and move its status through the hiring stages.' },
  { surface: 'website-app', path: '/navigation', label: 'Navigation',
    description: 'Add, edit, reorder and delete the header and footer links for each marketing website via per-site tabs; changes go live on the next site deploy.' },
  { surface: 'website-app', path: '/profile', label: 'Profile',
    description: 'Edit your name and profile photo, change your interface language, see your assigned roles and linked Google account, and sign out.' },

  // ---- Legal (legal) --------------------------------------------------
  { surface: 'legal', path: '/', label: 'Dashboard',
    description: 'See the total document count and searchable breakdowns of documents by type and policies by type, and click through to the Documents or Policies lists.' },
  { surface: 'legal', path: '/documents', label: 'Documents',
    description: 'Create a legal document with a name, type, description and rich-text content, then browse, search, edit, open or sign the documents in the table.' },
  { surface: 'legal', path: '/policies', label: 'Policies',
    description: 'Create, edit and delete the website and app policies — title, auto-generated slug, policy type, rich content, active state and sort order — that the public surfaces render.' },
  { surface: 'legal', path: '/contracts', label: 'Contracts',
    description: 'Add a contract with counterparty, status, effective dates and content, then view it read-only, edit it, or archive it while it keeps its contract ID.' },
  { surface: 'legal', path: '/grievance/tickets', label: 'Grievance Tickets', group: 'Grievance',
    description: 'Browse every grievance raised from the app, website or portal by reference number and received date, open one for its full detail and update it.' },
  { surface: 'legal', path: '/grievance/info', label: 'Grievance Info', group: 'Grievance',
    description: 'Enter and save the published Grievance Officer\'s name, email, phone and address that appear in the app, on the website and in every grievance acknowledgement.' },
  { surface: 'legal', path: '/profile', label: 'Profile',
    description: 'View and edit your own account — name and profile photo, display language, assigned roles and linked Google account — and sign out.' },

  // ---- AI (ai) --------------------------------------------------------
  { surface: 'ai', path: '/', label: 'Welcome',
    description: 'Land on a greeting dashboard card naming the AI portal and confirming the console is set up, with features still to come.' },
  { surface: 'ai', path: '/library', label: 'AI Library',
    description: 'Search, add, edit and delete AI prompts — including the System prompts the shipped AI features (image scanning, dummy data, moderation, support chat) read live — and reset a System prompt to its shipped default.' },
  { surface: 'ai', path: '/profile', label: 'Profile',
    description: 'View and edit your own account — name and profile photo, display language, assigned roles and linked Google account — and sign out.' },

  // ---- Products (products) --------------------------------------------
  { surface: 'products', path: '/', label: 'Dashboard',
    description: 'See aggregated catalogue KPIs on a rearrangeable grid — product count and stock value, order revenue, brand counts, and how many products are low or out of stock.' },
  { surface: 'products', path: '/inventory', label: 'Duncit Products', group: 'Catalog',
    description: 'Browse the Duncit-owned product catalogue with available and requested units, add a product, edit one, temporarily deactivate or reactivate it (hiding it from the shop and pod product picker), or archive it.' },
  { surface: 'products', path: '/catalog/brands', label: 'Brands', group: 'Catalog',
    description: 'Browse every seller brand in the catalogue at any review status (draft, submitted, approved, rejected, deactivated) and jump into a brand\'s own product list or its detail page to manage it.' },
  { surface: 'products', path: '/ecomm/brands', label: 'Brands Review', group: 'Brands & Products Review',
    description: 'Work the brand onboarding queue filtered by SUBMITTED/APPROVED/REJECTED/DRAFT/ALL and approve or reject each e-commerce brand a partner submitted.' },
  { surface: 'products', path: '/ecomm/product-requests', label: 'Products Reviews', group: 'Brands & Products Review',
    description: 'Work the product listing queue filtered by PENDING/APPROVED/DENIED/ALL and approve or deny each listing before it becomes selectable in pods.' },
  { surface: 'products', path: '/ecomm/brand-request', label: 'Brand Request', group: 'Ecomm Requests',
    description: 'Pick a brand and propose edits to its name, tagline, description or website URL, which are submitted for admin approval rather than applied directly.' },
  { surface: 'products', path: '/ecomm/product-request', label: 'Product Request', group: 'Ecomm Requests',
    description: 'Pick a product and propose edits to its name, short description, description or selling price, which are submitted for admin approval rather than applied directly.' },
  { surface: 'products', path: '/warehouse-approval', label: 'Warehouse Approval',
    description: 'Filter partner warehouse requests by PENDING/APPROVED/DENIED/ALL and approve a warehouse so it can be used for shipping, or deny it to keep it blocked.' },
  { surface: 'products', path: '/orders', label: 'Orders', group: 'Fulfilment',
    description: 'Browse every product order placed inside a pod and open an order for its fulfilment detail — shipping or pickup ops.' },
  { surface: 'products', path: '/settings/warehouses', label: 'Duncit Warehouse Locations', group: 'Settings',
    description: 'Add and manage the Duncit-owned warehouses first-party products ship from, and register them with ShipRocket so SHIP orders can be picked up and live delivery rates work.' },
  { surface: 'products', path: '/settings/pod-shop-slider', label: 'Pod Shop Slider', group: 'Settings',
    description: 'Curate the image/video slider at the top of the platform-wide Pod Shop on the app and mWeb — add media with heading, subheading and CTA label/URL, and reorder items with the arrows.' },
  { surface: 'products', path: '/inventory/new', label: 'Add Product',
    description: 'Fill in the validated product form to create a new Duncit catalogue product — name, descriptions, category, pricing, stock and shipping origin — with media upload.' },
  { surface: 'products', path: '/profile', label: 'Profile',
    description: 'View and edit your own signed-in account — name, profile photo, email, roles, linked Google account and interface language — or sign out.' },

  // ---- Onboarding (onboarding) ----------------------------------------
  { surface: 'onboarding', path: '/', label: 'Dashboard',
    description: 'Read onboarding KPIs, a meeting-schedule strip whose cards jump straight to that kind\'s requested meetings, per-status donut cards for hosts / venues / e-commerce brands that open the matching list, and a 6-month onboarding trend chart — all as rearrangeable widgets.' },
  { surface: 'onboarding', path: '/surveys', label: 'Surveys',
    description: 'Pick which audience a survey is for — Venue, Host, E-Commerce Brand or Club Admin — from four cards, each opening that kind\'s survey list.' },
  { surface: 'onboarding', path: '/surveys/kind/venue', label: 'Venue Surveys', group: 'Surveys',
    description: 'Browse, filter by Super/Category/Sub scope, open, delete or create category-specific Venue onboarding surveys, and edit the kind-level default survey via the Default Survey button.' },
  { surface: 'onboarding', path: '/surveys/kind/host', label: 'Host Surveys', group: 'Surveys',
    description: 'Browse, filter by Super/Category/Sub scope, open, delete or create category-specific Host onboarding surveys, and edit the kind-level default survey via the Default Survey button.' },
  { surface: 'onboarding', path: '/surveys/kind/seller', label: 'E-Commerce Brand Surveys', group: 'Surveys',
    description: 'Browse, filter by Super/Category/Sub scope, open, delete or create category-specific E-Commerce Brand onboarding surveys, and edit the kind-level default survey via the Default Survey button.' },
  { surface: 'onboarding', path: '/surveys/kind/club-admin', label: 'Club Admin Surveys', group: 'Surveys',
    description: 'Browse, filter by Super/Category/Sub scope, open, delete or create category-specific Club Admin onboarding surveys, and edit the kind-level default survey via the Default Survey button.' },
  { surface: 'onboarding', path: '/surveys/new', label: 'New Survey', group: 'Surveys',
    description: 'Build a survey: set its kind, title and active toggle, scope it to a Super/Category/Sub slot, then add, reorder and delete section-heading, multiple-choice, short-text and long-text questions with help text and required/multi flags before saving.' },
  { surface: 'onboarding', path: '/meetings/calendar', label: 'Calendar', group: 'Meeting Schedule',
    description: 'View every onboarding meeting in Outlook-style Day, Week or Month grids with holidays, availability shading and a live current-time line; click an event for its details drawer, or right-click a cancelled meeting to remove it from your calendar.' },
  { surface: 'onboarding', path: '/meetings/venue', label: 'Venue Meetings', group: 'Meeting Schedule',
    description: 'Work the Venue onboarding meeting queue: filter by Requested/Scheduled/Done/Rejected/Cancelled, open a requester\'s contact details, schedule or reschedule a slot, record an approve/reject decision, mark a meeting done, or cancel it.' },
  { surface: 'onboarding', path: '/meetings/host', label: 'Host Meetings', group: 'Meeting Schedule',
    description: 'Work the Host onboarding meeting queue: filter by Requested/Scheduled/Done/Rejected/Cancelled, open a requester\'s contact details, schedule or reschedule a slot, record an approve/reject decision, mark a meeting done, or cancel it.' },
  { surface: 'onboarding', path: '/meetings/ecomm', label: 'E-Commerce Brand Meetings', group: 'Meeting Schedule',
    description: 'Work the E-Commerce Brand onboarding meeting queue: filter by status, open the requester\'s contact details, schedule or reschedule a slot, record an approve/reject decision, mark a meeting done, or cancel it.' },
  { surface: 'onboarding', path: '/meetings/club_admin', label: 'Club Admin Meetings', group: 'Meeting Schedule',
    description: 'Work the Club Admin onboarding meeting queue: filter by status, open the requester\'s contact details, schedule or reschedule a slot, record an approve/reject decision, mark a meeting done, or cancel it.' },
  { surface: 'onboarding', path: '/meetings/availability', label: 'Meeting Availability', group: 'Meeting Schedule',
    description: 'Set the global bookable-slot rules applicants see — working weekdays, IST start and end time, slot length in minutes and the booking horizon in days — and manage meeting holidays in the card below.' },
  { surface: 'onboarding', path: '/host-requests', label: 'Host Additional Requests', group: 'Onboarding',
    description: 'Review requests from already-approved hosts to start hosting in a new category: acknowledge a request to reveal contact details, then approve or reject it with notes, or permanently delete the request.' },
  { surface: 'onboarding', path: '/hosts', label: 'Onboarded Hosts', group: 'Onboarding',
    description: 'Review submitted host applications and manage approved hosts — open the review dialog to approve/reject with notes and tags, set their commission percentage and categories, edit host details, or deactivate/hard-delete a host.' },
  { surface: 'onboarding', path: '/venues', label: 'Onboarded Venues', group: 'Onboarding',
    description: 'Review submitted venue registrations and manage approved spaces — approve/reject with notes and tags, set the venue share and commission percentages, edit venue details, or deactivate/hard-delete a venue.' },
  { surface: 'onboarding', path: '/ecomm-brands', label: 'Onboarded E-Commerce Brands', group: 'Onboarding',
    description: 'Verify partner product brands before they go live — approve/reject with notes and tags, set the product commission percentage, edit brand details, or deactivate/hard-delete a brand (which hides its products from the marketplace).' },
  { surface: 'onboarding', path: '/club-admins', label: 'Onboarded Club Admins', group: 'Onboarding',
    description: 'Manage everyone approved through the Club Admin meeting flow — approve or reject with notes, set their commission percentage, assign which clubs they administer, edit their details, or deactivate/hard-delete them.' },
  { surface: 'onboarding', path: '/profile', label: 'Profile',
    description: 'Edit your first and last name, view your email, linked Google account and access-role chips, change your display language, and sign out of the Onboarding console.' },

  // ---- HR (hr) --------------------------------------------------------
  { surface: 'hr', path: '/', label: 'Dashboard',
    description: 'See a personalised welcome with your access-role chips and an account summary card (name, email, phone, joined date) in a drag-and-resize widget grid whose layout is saved per user; no HR modules are configured yet, so nothing else renders.' },
  { surface: 'hr', path: '/profile', label: 'Profile',
    description: 'Edit your first and last name, view your email, linked Google account and access-role chips, change your display language, and sign out of the HR console.' },

  // ---- Employee (employee) --------------------------------------------
  { surface: 'employee', path: '/', label: 'Dashboard',
    description: 'See a personalised welcome with your access-role chips and an account summary card (name, email, phone, joined date) in a drag-and-resize widget grid whose layout is saved per user; no employee modules are configured yet, so nothing else renders.' },
  { surface: 'employee', path: '/profile', label: 'Profile',
    description: 'Edit your first and last name, view your email, linked Google account and access-role chips, change your display language, and sign out of the Employee console.' },

  // ---- Partners (partners) --------------------------------------------
  { surface: 'partners', path: '/venues/dashboard', label: 'Venue Dashboard', group: 'Venue Owner',
    description: 'Pick one venue (or all together) and read its slot-based earnings potential, capacity and pending booking-request counts, with quick jumps to Venue Management, Slot Requests and the availability calendar.' },
  { surface: 'partners', path: '/venues/auto-pods', label: 'Auto Pods', group: 'Venue Owner',
    description: 'Browse Auto Pod offers your venue can accept — an admin-written pod with no venue yet — and accept one by committing a free slot, which fixes its date and opens it to a host and a club admin.' },
  { surface: 'partners', path: '/register-venue', label: 'Venue Management', group: 'Venue Owner',
    description: 'See the table of every venue registration on your account with its review status and open one to continue or edit the application.' },
  { surface: 'partners', path: '/register-venue/new', label: 'Register Venue', group: 'Venue Owner',
    description: 'Fill in the multi-section venue registration form — venue type, description, images, capacity items, amenities, owner details and documents — and submit the space for review.' },
  { surface: 'partners', path: '/register-venue/current', label: 'Current Venue Application', group: 'Venue Owner',
    description: 'Reopen the venue application currently attached to your account to keep editing a draft, view it while it is under review, or fix and resubmit a rejected one.' },
  { surface: 'partners', path: '/venues/requests', label: 'Slot Requests', group: 'Venue Owner',
    description: 'Review hosts who booked a slot at your venue and approve the booking (which puts the pod live) or decline it with a reason, filtered by venue.' },
  { surface: 'partners', path: '/venues/pods', label: 'Pods', group: 'Venue Owner',
    description: 'Browse every pod booked at your venues across All/upcoming/completed/cancelled tabs, click a pod for its attendee list, and cancel a pod you can no longer host.' },
  { surface: 'partners', path: '/host/dashboard', label: 'Dashboard', group: 'Host',
    description: 'See your available wallet balance, host earnings and pod status tiles, 12-month insight charts and account-health card, and jump straight to creating a pod.' },
  { surface: 'partners', path: '/host/auto-pods', label: 'Auto Pods', group: 'Host',
    description: 'See Auto Pods a venue has already accepted and take one with Assign Myself — the venue, date and price are fixed, and the card shows what you would earn before you commit.' },
  { surface: 'partners', path: '/become-host', label: 'Become a Host',
    description: 'Work through the four-step host application — personal details, Aadhaar/PAN plus passport photo, police verification and address — then submit it for review or withdraw a pending one.' },
  { surface: 'partners', path: '/host/pods', label: 'Your Pods', group: 'Host',
    description: 'Create a new pod and manage every pod you host from one table — scan tickets, complete a pod, edit or resubmit a venue-rejected pod, share the rating link, and cancel.' },
  { surface: 'partners', path: '/ecomm/dashboard', label: 'Dashboard', group: 'E-Commerce Brand',
    description: 'Read owner-scoped KPI cards for how your brands, products, warehouses and orders are performing on Duncit.' },
  { surface: 'partners', path: '/ecomm-brand', label: 'Your Brands', group: 'E-Commerce Brand',
    description: 'Register a new product brand or open an existing one to edit, submit for review, withdraw from review, pause/reactivate it, or jump to its products and warehouse settings.' },
  { surface: 'partners', path: '/earn', label: 'Earn with Duncit',
    description: 'Browse the earn-journey cards (host, list your venue, sell products, club) and start the matching survey on mWeb or jump into the partner area you are already approved for.' },
  { surface: 'partners', path: '/verification', label: 'Verification',
    description: 'Upload an identity document and enter your residential address for admin approval, and see the verified state of your identity, address and email.' },
  { surface: 'partners', path: '/wallet', label: 'Wallet',
    description: 'Check your available balance and payout cycle, request a withdrawal above the role-wise minimum, and review past withdrawals and wallet transactions.' },
  { surface: 'partners', path: '/club-admin/dashboard', label: 'Dashboard', group: 'Club Admin',
    description: 'Pick a date range and read pod, booking, community and revenue KPIs plus a trend chart and per-club table across every club you administer.' },
  { surface: 'partners', path: '/club-admin/auto-pods', label: 'Auto Pods', group: 'Club Admin',
    description: 'Claim a venue-accepted Auto Pod for one of the clubs you administer; the pod is created under that club once a host has enrolled too.' },
  { surface: 'partners', path: '/club-admin/clubs', label: 'Clubs', group: 'Club Admin',
    description: 'Browse the searchable table of clubs assigned to you and click one to open its details for editing or jump to that club\'s pods.' },
  { surface: 'partners', path: '/club-admin/monitoring', label: 'Pod Monitoring (AI)', group: 'Club Admin',
    description: 'Scan the AI risk-scored audit trail of every pod edit, status change and critical action in your clubs and open a row for the full audit detail.' },
  { surface: 'partners', path: '/faqs', label: 'FAQs',
    description: 'Search partner FAQs and filter them by Venue, Host or Products topic, expanding each question for its answer.' },
  { surface: 'partners', path: '/support', label: 'Support',
    description: 'Submit a support request about host, venue, product, payout or technical issues; replies go to your account email, which is pre-filled and locked.' },
  { surface: 'partners', path: '/policies', label: 'Policies',
    description: 'Read the admin-managed partner policy documents, picking each one from the side list.' },
  { surface: 'partners', path: '/profile', label: 'Profile',
    description: 'Edit your name and profile photo, change your interface language, see your assigned roles and linked Google account, and sign out.' },

  // ---- Challenges (challenge) -----------------------------------------
  { surface: 'challenge', path: '/', label: 'Dashboard',
    description: 'See total-challenges and active-challenges stat tiles as rearrangeable widgets; clicking either tile opens the Challenges list.' },
  { surface: 'challenge', path: '/challenges', label: 'Challenges',
    description: 'Browse the challenges table and create a new challenge or edit an existing one (name, description and a cascading Super → Category → Sub-category scope), or permanently delete one after confirming.' },
  { surface: 'challenge', path: '/leaderboard', label: 'Boards', group: 'Leaderboard',
    description: 'Read headline stats per board and browse one live board at a time — pick a leaderboard category and ranking window (period) to see the ranked rows with user, rank and points.' },
  { surface: 'challenge', path: '/leaderboard/points', label: 'Points Ledger', group: 'Leaderboard',
    description: 'Browse every leaderboard points award newest-first in a sortable, filterable table to audit who earned what and why.' },
  { surface: 'challenge', path: '/leaderboard/settings', label: 'Settings & Rewards', group: 'Leaderboard',
    description: 'Set how many points each tracked action earns and edit the reward rows that pay out for finishing a ranking window inside a given rank range — each card saves independently.' },
  { surface: 'challenge', path: '/profile', label: 'Profile',
    description: 'Edit your first and last name, view your email, linked Google account and access-role chips, change your display language, and sign out of the Challenges console.' },

  // ---- Developers (developers) ----------------------------------------
  { surface: 'developers', path: '/', label: 'Dashboard',
    description: 'Jump into either of the two developer areas from tiles for API Keys and the API Reference.' },
  { surface: 'developers', path: '/keys', label: 'API Keys',
    description: 'Create a named API key, copy its raw value once at creation, and revoke existing keys used to authenticate /api/v1 requests with the x-api-key header.' },
  { surface: 'developers', path: '/docs', label: 'API Reference',
    description: 'Read the /api/v1 endpoint docs (list venues, get a venue, slot availability, book a slot, cancel a booking) with sample curl and responses, then call them live from the Try-It panel using your own API key.' },
  { surface: 'developers', path: '/profile', label: 'Profile',
    description: 'View and edit your own account — name and profile photo, display language, assigned roles and linked Google account — and sign out.' },
];
