import type { NavigationPage } from './askBot.catalog';

/**
 * Every screen members can reach, in the web app and in the native app.
 *
 * mWeb and the mobile app are deliberately identical (rule 27), so the two lists
 * mirror each other — but they are kept apart rather than merged, because the
 * bot is asked "where is this in the app?" as often as "where is this on the
 * site", and the answer names a different thing each time. The app's paths are
 * its deep links (`app/mobile-app/src/navigation/linking.ts`), which are the
 * same URL grammar mWeb uses, so an mweb.duncit.com link opens the app screen.
 */

export const APP_PAGES: readonly NavigationPage[] = [
  // ---- Duncit Member Web App (mWeb) (mweb) ----------------------------
  { surface: 'mweb', path: '/', label: 'Home',
    description: 'Browse the personalised pod feed for the chosen city and super-category — stories rail, featured pods, vibe chips, club sections, previous-pods rail — filter by category/price/date/sort, search, and tap the floating + to create a pod.' },
  { surface: 'mweb', path: '/explore', label: 'Explore',
    description: 'Swipe a full-screen vertical reels feed of live pods, filter by preset/category/price/date/sort, and heart a pod to save it without leaving the feed.' },
  { surface: 'mweb', path: '/clubs', label: 'Clubs',
    description: 'Search and browse every active club in the selected city, narrow them with super-category chips, and tap a club card to open its page.' },
  { surface: 'mweb', path: '/chats', label: 'Chats',
    description: 'See every pod chat room you belong to, filter them by All / Upcoming Pods / Previous Pods, search by pod title, and open one to talk to the group.' },
  { surface: 'mweb', path: '/chats/:id', label: 'Pod Chat Room',
    description: 'Open the live chat for pod :id (the pod\'s document id) to send text and media messages, react with emoji, view participants, and jump to the pod\'s detail page; the room closes once the pod has ended.' },
  { surface: 'mweb', path: '/follow', label: 'Following',
    description: 'Read the activity feed of the clubs and people you follow on two tabs (Clubs / People) and tap any post to open it in the post dialog.' },
  { surface: 'mweb', path: '/menu', label: 'Account Menu',
    description: 'Open the full-screen account menu to reach your profile, quick actions, Duncit Coin, referral, Manage Account and Shop lists, switch studio role, toggle dark mode, read policies and log out.' },
  { surface: 'mweb', path: '/search', label: 'Search',
    description: 'Type to search pods and clubs with live suggestions, use category quick actions, sort and filter results, and follow a club straight from the result card.' },
  { surface: 'mweb', path: '/happening-nearby', label: 'Happening Nearby',
    description: 'See every upcoming (live) pod for the selected city and super-category in one list, narrowed by the same category/price/date/sort filters as Home.' },
  { surface: 'mweb', path: '/previous-pods', label: 'Previous Pods',
    description: 'Browse pods that have already taken place in the selected city and super-category, newest first, with category/price/date filters.' },
  { surface: 'mweb', path: '/venues', label: 'Venues',
    description: 'Explore public venues for the chosen location — search by name, type or area, filter by super-category chip, and open a venue card to see its details.' },
  { surface: 'mweb', path: '/venue/:venueId', label: 'Venue Details',
    description: 'View a single venue\'s photos, capacity, description, amenities, facilities, security, map preview and the pods scheduled there; copy the address to share it. This is the one page that opens without signing in.' },
  { surface: 'mweb', path: '/club/:clubSlug', label: 'Club Details',
    description: 'Open a club by its slug to follow/save it, watch its stories and moments, read its bullets, FAQs, rating and social links, and browse its upcoming pods, members, admins, hosts and meetup venues.' },
  { surface: 'mweb', path: '/club/:clubSlug/pod/:podSlug', label: 'Pod Details',
    description: 'Open a specific pod (club slug + pod id) to read the full brief, pick seats and book it, save it, buy products from its shop, post to the pod status, and back out or keep your spot if you already joined.' },
  { surface: 'mweb', path: '/pod/:podId/feedback', label: 'Rate a Pod',
    description: 'Rate a pod you attended aspect by aspect and leave a message from the link the host shares; opening it again shows the rating you already gave so you can edit it.' },
  { surface: 'mweb', path: '/booking/:bookingId', label: 'Booking Redirect',
    description: 'Deep link from the payment-receipt email\'s "View Booking" button — it resolves the booking server-side (rejecting anyone who does not own it) and forwards you to that pod\'s detail page.' },
  { surface: 'mweb', path: '/pod-history', label: 'Pod History', group: 'Menu',
    description: 'Search and filter every pod you have joined, with its status, and tap one to open its full booking record.' },
  { surface: 'mweb', path: '/pod-history/:membershipId', label: 'Pod History Details', group: 'Menu',
    description: 'See one pod membership in full — timeline, payment, product orders and actions — and back out of the pod or rejoin it from here.' },
  { surface: 'mweb', path: '/saved', label: 'Saved Items', group: 'Manage Account',
    description: 'Browse the pods you have saved, search them, filter by category and sort the list, then tap through to any pod.' },
  { surface: 'mweb', path: '/pod-ideas', label: 'Pod Ideas', group: 'Menu',
    description: 'Post your own pod idea against a Super → Category → Sub selection, browse and search other people\'s ideas, like, share, open and delete your own.' },
  { surface: 'mweb', path: '/profile', label: 'My Profile', group: 'Menu',
    description: 'View your own profile header, stats and posts grid, upload a new post, open a post, and jump to account settings.' },
  { surface: 'mweb', path: '/u/:userId', label: 'Member Profile',
    description: 'View another member\'s public profile — bio, city, follower/following counts, badges and posts — and follow, unfollow or cancel a pending follow request.' },
  { surface: 'mweb', path: '/post/:postId', label: 'Post',
    description: 'Deep-link target for post notifications: opens a single post with its comment thread in the post dialog, where you can comment, like or delete your own.' },
  { surface: 'mweb', path: '/account', label: 'Manage Account', group: 'Manage Account',
    description: 'Edit your name, email, phone, WhatsApp, city and date of birth, watch your profile-completion meter and account-health score, set privacy, change your password, manage connected accounts, pick your language and open Communication Preferences. Your @handle is assigned automatically and is shown, with the link that copies it, on your profile.' },
  { surface: 'mweb', path: '/account/health', label: 'Account Health', group: 'Manage Account',
    description: 'See your account-health score with the full breakdown of what raises or lowers it.' },
  { surface: 'mweb', path: '/account/communication', label: 'Communication Preferences', group: 'Manage Account',
    description: 'The hub reached from one row in Profile Settings: it lists Email, WhatsApp and SMS with where each one goes and whether authentication messages arrive there, and opens each channel screen.' },
  { surface: 'mweb', path: '/account/mail-preference', label: 'Mail Preference', group: 'Manage Account',
    description: 'Choose which categories of Duncit email you want to keep receiving, switch any of them off, and decide whether authentication messages may reach you by email.' },
  { surface: 'mweb', path: '/account/sms-preference', label: 'SMS Preference', group: 'Manage Account',
    description: 'Decide whether authentication messages may reach you by text. They are the only texts Duncit sends, and the switch is refused when SMS is the last channel that can reach you.' },
  { surface: 'mweb', path: '/unsubscribe', label: 'Unsubscribe',
    description: 'The one-click opt-out an email footer links to — it reads the signature from the query string, so it works without signing in.' },
  { surface: 'mweb', path: '/verification', label: 'Verification', group: 'Manage Account',
    description: 'Upload an identity document (max 4 MB), submit your residential address for admin review, and check whether your email is verified.' },
  { surface: 'mweb', path: '/tour-guide', label: 'Tour Guide', group: 'Manage Account',
    description: 'Browse every guided walkthrough available for your roles and start or replay any of them — it navigates to that screen and arms the tour.' },
  { surface: 'mweb', path: '/faqs', label: 'FAQs', group: 'Manage Account',
    description: 'Search the public FAQ library and expand any question, grouped by super-category.' },
  { surface: 'mweb', path: '/badges', label: 'Badges', group: 'Manage Account',
    description: 'Every Duncit badge with the goal it asks for, the window that goal must happen in, and how far along the member is — earned ones read Achieved with the date, and also appear on their profile.' },
  { surface: 'mweb', path: '/policies/:slug', label: 'Policy', group: 'Manage Account',
    description: 'Read a published legal/policy document by its slug (terms, privacy, refund and the rest, as listed in the account menu).' },
  { surface: 'mweb', path: '/pod-plans', label: 'Pod Plans', group: 'Manage Account',
    description: 'Compare the published pod plans with their features and price labels (flag-gated by pod_plans_section; some show as coming soon).' },
  { surface: 'mweb', path: '/duncit-coin', label: 'Duncit Coin', group: 'Menu',
    description: 'Check your Duncit Coin balance and read the full ledger of coins earned on payments and spent at checkout.' },
  { surface: 'mweb', path: '/referral', label: 'Refer & Earn', group: 'Menu',
    description: 'Copy or share your personal referral code and link, see the reward per referral, and track who has already joined through it.' },
  { surface: 'mweb', path: '/leaderboard', label: 'Leaderboard', group: 'Leaderboard',
    description: 'See your points and rank on five boards (Users, Hosts, Club Admins, Venues, Brands) for this month / this year / all time, plus how to earn points and what the rewards are (flag-gated by leaderboard).' },
  { surface: 'mweb', path: '/membership', label: 'Membership', group: 'Membership',
    description: 'Preview the membership tiers, their provisional prices and the full benefit comparison table, and leave your email to be notified when it opens — the buy CTAs are deliberately disabled (flag-gated by membership).' },
  { surface: 'mweb', path: '/shop', label: 'Pod Shop', group: 'Shop',
    description: 'Browse the product catalogue with the pod-shop slider, search by product or brand, filter and sort, and quick-add an item to your cart from the cheapest stocking pod.' },
  { surface: 'mweb', path: '/product/:productId', label: 'Product Detail', group: 'Shop',
    description: 'Read a single product\'s images, specs, variants, price, stock, brand info and reviews, and add it to the cart via one of the pods that stock it.' },
  { surface: 'mweb', path: '/cart', label: 'Cart', group: 'Shop',
    description: 'Review every product you have added, grouped by pod, change quantities, remove lines or clear the cart, then go to the combined product checkout.' },
  { surface: 'mweb', path: '/product-checkout', label: 'Product Checkout', group: 'Shop',
    description: 'Pay for the whole cart in one product payment — pick a saved delivery address, see the per-warehouse delivery quote and breakup, redeem Duncit Coins and pay via Razorpay.' },
  { surface: 'mweb', path: '/orders', label: 'My Product Order History', group: 'Shop',
    description: 'See every product order you have placed across all pods, newest first, each with its fulfilment tracking timeline.' },
  { surface: 'mweb', path: '/address-book', label: 'Address Book', group: 'Shop',
    description: 'Add, edit and delete the delivery addresses used at product checkout.' },
  { surface: 'mweb', path: '/checkout', label: 'Pod Checkout', group: 'Shop',
    description: 'Pay for a pod booking (pod carried in navigation state or ?pod_id) — fill contact and billing details, see the price breakup, redeem Duncit Coins and pay via Razorpay.' },
  { surface: 'mweb', path: '/checkout/:podId', label: 'Pod Checkout (by pod)', group: 'Shop',
    description: 'The same pod checkout addressed directly by :podId — contact, billing, coin redemption and the Razorpay payment for that specific pod\'s seats.' },
  { surface: 'mweb', path: '/gift-cards', label: 'Gift Cards', group: 'Gift Cards',
    description: 'Buy a themed gift card (any category or the Pod Shop), pick an amount, keep it or send it as a gift, and review the cards you hold or gifted (flag-gated by gift_cards).' },
  { surface: 'mweb', path: '/gift-cards/checkout', label: 'Gift Card Checkout', group: 'Gift Cards',
    description: 'Pay for the chosen gift card — review the theme, amount and recipient, then complete the payment; the card and its code are emailed on success.' },
  { surface: 'mweb', path: '/gift-cards/redeem', label: 'Redeem Gift Card', group: 'Gift Cards',
    description: 'Enter a gift card code, check the card, and convert its full value into Duncit Coins — with the how-it-works instructions.' },
  { surface: 'mweb', path: '/gift-card/:code', label: 'Gift Card Claim', group: 'Gift Cards',
    description: 'Open a gift card shared by email or link, see who sent it, its value and expiry, and redeem it into Duncit Coins.' },
  { surface: 'mweb', path: '/support', label: 'Help & Support', group: 'Menu',
    description: 'Search the help centre, read the top FAQs, and pick a way to reach the team — SOS, callback, tickets, live chat, grievance or report a problem.' },
  { surface: 'mweb', path: '/support/sos', label: 'SOS', group: 'Support',
    description: 'Raise an emergency SOS tied to the live pod you pick, so the team can act on it immediately.' },
  { surface: 'mweb', path: '/support/callback', label: 'Callback Request', group: 'Support',
    description: 'Ask the support team to call you back (not tied to any pod) and see your earlier callback requests.' },
  { surface: 'mweb', path: '/support/tickets', label: 'Create Support Ticket', group: 'Support',
    description: 'Raise a support ticket with category, subject, message and an optional pod attached (pre-fillable from ?category/?subject/?message/?podId), and see your ticket list.' },
  { surface: 'mweb', path: '/support/live', label: 'Chat with Us', group: 'Support',
    description: 'Start a real-time chat with a support agent from this single entry card.' },
  { surface: 'mweb', path: '/support/all', label: 'All Support Tickets', group: 'Support',
    description: 'See every support request you have raised — tickets, SOS, callbacks and chats — in one chronological list, and open any of them.' },
  { surface: 'mweb', path: '/support/grievance', label: 'Raise a Grievance', group: 'Support',
    description: 'File a formal grievance with the named Grievance Officer and get the reference number on screen and by email.' },
  { surface: 'mweb', path: '/support/feedback', label: 'Report a Problem', group: 'Support',
    description: 'Send the team a categorised feedback note (with optional media links) that lands in their Slack; your identity is stamped by the server.' },
  { surface: 'mweb', path: '/tickets/:id', label: 'Ticket Detail', group: 'Support',
    description: 'Read one ticket\'s full thread live, reply to the agent, resolve or reopen it, rate it, and download or email yourself the transcript.' },
  { surface: 'mweb', path: '/live-chat', label: 'Live Support Chat', group: 'Support',
    description: 'Chat with a support agent in real time — send messages, see typing, close the session, rate it, reopen it with a reason and email yourself the transcript.' },
  { surface: 'mweb', path: '/tickets', label: 'Tickets (redirect)', group: 'Support',
    description: 'Legacy alias that immediately redirects to /support/live.' },
  { surface: 'mweb', path: '/support/chat', label: 'Support Chat (redirect)', group: 'Support',
    description: 'Native-parity alias that immediately redirects to /support/live.' },
  { surface: 'mweb', path: '/bouncers', label: 'Bouncers (redirect)', group: 'Support',
    description: 'Legacy alias that immediately redirects to /support.' },
  { surface: 'mweb', path: '/earn', label: 'Earn with Duncit', group: 'Menu',
    description: 'See every way to earn — host, register a venue, sell products, run a club — start the matching onboarding survey in-app, or jump to the Partner Portal once a role is approved.' },
  { surface: 'mweb', path: '/hosts-venues', label: 'Hosts & Venues',
    description: 'Browse the public directory of hosts and venues on two counted tabs, follow or unfollow a host, check your onboarding meeting status, and start the Become-a-Host or Register-a-Venue survey.' },
  { surface: 'mweb', path: '/survey/:kind', label: 'Partner Onboarding Survey',
    description: 'The onboarding gate for :kind (host, venue, ecomm or club_admin) — pick Super → Category → Sub, answer that category\'s survey, then book an onboarding meeting slot and land on a thank-you.' },
  { surface: 'mweb', path: '/become-host', label: 'Become a Host (redirect)',
    description: 'Immediately redirects the browser to https://partners-app.duncit.com/become-host.' },
  { surface: 'mweb', path: '/register-venue', label: 'Register a Venue (redirect)',
    description: 'Immediately redirects the browser to https://partners-app.duncit.com/register-venue.' },
  { surface: 'mweb', path: '/create-pod', label: 'Create Pod', group: 'Host Menu',
    description: 'Walk the multi-step create-pod stepper — club, category, schedule, venue slot, spots, pricing, media and products — to publish a new pod as a host.' },
  { surface: 'mweb', path: '/create-pod/:draftId', label: 'Edit Pod Draft', group: 'Host Menu',
    description: 'Reopen saved draft :draftId in the create-pod stepper with every answer rehydrated and carry on from where you stopped.' },
  { surface: 'mweb', path: '/host/manage', label: 'Host Studio', group: 'Host Menu',
    description: 'The host home — your pods list (including ones offline awaiting or refused venue approval), drafts, approved host categories and share card, with buttons to the Host Dashboard and Create Pod.' },
  { surface: 'mweb', path: '/host/dashboard', label: 'Host Dashboard', group: 'Host Menu',
    description: 'Track your host earnings, pod stats, insights and profile/verification health, with quick actions to the rest of the host tools.' },
  { surface: 'mweb', path: '/host/apply', label: 'Apply for Another Category', group: 'Host Menu',
    description: 'As an already-approved host, pick another Super → Category → Sub, answer its survey and submit a host request without booking a second meeting.' },
  { surface: 'mweb', path: '/host/pod-pending/:podId', label: 'Pod Pending Approval', group: 'Host Menu',
    description: 'The waiting page after creating pod :podId whose venue slot request is still PENDING — status banner, pod summary, venue contact and club-admin help cards.' },
  { surface: 'mweb', path: '/host/wallet', label: 'Withdrawal / Wallet', group: 'Host Menu',
    description: 'See your earnings balance and payout cycle, request a withdrawal, and track each request\'s PENDING/PAID/REJECTED status — the shared wallet for every partner role.' },
  { surface: 'mweb', path: '/venues/manage', label: 'Venue Studio', group: 'Venue Menu',
    description: 'Manage your venue — its details, health score, monthly pod chart, the pods booked there, and links to earnings and adding another venue.' },
  { surface: 'mweb', path: '/venues/slot-requests', label: 'Slot Requests', group: 'Venue Menu',
    description: 'Work the queue of hosts\' slot requests for your venues — filter by venue and approve or decline each one, which is what lets that pod go live.' },
  { surface: 'mweb', path: '/venues/earnings', label: 'Venue Earnings', group: 'Venue Menu',
    description: 'See the earnings summary stat cards and payout history across every venue you own.' },
  { surface: 'mweb', path: '/venues/:venueId/health', label: 'Venue Health', group: 'Venue Menu',
    description: 'See venue :venueId\'s health score with the full breakdown of the items that raise or lower it.' },
  { surface: 'mweb', path: '/products/manage', label: 'Product Studio', group: 'E-commerce Menu',
    description: 'The brand/e-commerce dashboard — catalogue size, stock and price stats plus a stock-by-product chart (hidden when the is_product_visible flag is off).' },
  { surface: 'mweb', path: '/clubs/manage', label: 'Club Studio', group: 'Club Admin Menu',
    description: 'The Club Admin home — the pods belonging to your clubs with their summary, rendered through the same section the Venue Studio uses.' },
  { surface: 'mweb', path: '/login', label: 'Log In', group: 'Auth',
    description: 'Sign in with email and password or with Google (including linking Google to an existing account), then land back on the ?redirect target.' },
  { surface: 'mweb', path: '/register', label: 'Create Account', group: 'Auth',
    description: 'Create a Duncit account with your details or Google, optionally applying a referral code picked up from the link you arrived on.' },
  { surface: 'mweb', path: '/forgot-password', label: 'Forgot Password', group: 'Auth',
    description: 'Enter your email to be sent a password-reset OTP; an unregistered address is flagged with a Create-Account prompt instead.' },
  { surface: 'mweb', path: '/reset-password', label: 'Reset Password', group: 'Auth',
    description: 'Enter the OTP sent to ?email and set a new password, or resend the code.' },
  { surface: 'mweb', path: '/signup-survey', label: 'Interest Survey', group: 'Auth',
    description: 'Pick your interest categories (a minimum number is required) right after signing up so the feed can be personalised.' },
  { surface: 'mweb', path: '/signup-whatsapp', label: 'Verify WhatsApp', group: 'Auth',
    description: 'Request a WhatsApp OTP for your number and verify it, or skip the step, as part of finishing signup.' },
  { surface: 'mweb', path: '/signup-referral', label: 'Referral Code (signup)', group: 'Auth',
    description: 'Enter a friend\'s referral code after a Google signup finished without one — or skip it.' },

  // ---- Duncit Native Mobile App (app) ---------------------------------
  { surface: 'app', path: '/', label: 'Home',
    description: 'On the Home tab a member scrolls the live pod feed — story/status rail, vibe category chips, a price/date/sort filter sheet, the "Happening nearby" section, featured pods, a previous-pods rail, per-club pod rows and sponsored slots — and taps the floating "+" to create a pod.' },
  { surface: 'app', path: '/explore', label: 'Explore',
    description: 'On the Explore tab a member swipes through a vertical full-screen Reels feed of pod videos and opens a pod straight from the reel.' },
  { surface: 'app', path: '/clubs', label: 'Clubs',
    description: 'On the Clubs tab a member browses active clubs in the selected Country > City > Area location, searches by name, filters by category, and taps a club to open its page.' },
  { surface: 'app', path: '/chats', label: 'Chats',
    description: 'On the Chats tab a member sees every pod chat room they belong to, searches rooms by pod title, narrows to Upcoming or Previous pods, and taps a room to open the conversation.' },
  { surface: 'app', path: '/following', label: 'Following',
    description: 'On the Following tab a member reads a social feed of posts and active stories from the People or Clubs they follow, likes posts, opens the comment viewer, and taps through to the author\'s profile or club.' },
  { surface: 'app', path: '/menu', label: 'Menu',
    description: 'On the Menu (account drawer) screen a member reaches the quick tiles Pod History, Help & Support, Earn with Duncit and Pod Ideas, the Duncit Coin and Refer & Earn cards, the Manage Account and Shop lists, the policies footer, and the partner studio menu for whichever studio mode they are switched into.' },
  { surface: 'app', path: '/search', label: 'Search',
    description: 'On the Search screen a member types a query to get live suggestions, taps category quick-actions, and browses club-grouped results (Happening This Week / More Clubs) with sort and filter controls.' },
  { surface: 'app', path: '/login', label: 'Login', group: 'Sign in',
    description: 'On the Login screen a person signs in with email and password or with Google (granting consent to link Google to an existing email account), or jumps to Sign up / Forgot password.' },
  { surface: 'app', path: '/signup', label: 'Sign Up', group: 'Sign in',
    description: 'On the Sign Up screen a person creates an account with name, date of birth, email, password and an optional referral code, or signs up with Google.' },
  { surface: 'app', path: '/forgot-password', label: 'Forgot Password', group: 'Sign in',
    description: 'On the Forgot Password screen a person enters their email to have a reset OTP sent; an unregistered address is flagged with a Create-Account shortcut instead.' },
  { surface: 'app', path: '/reset-password', label: 'Reset Password', group: 'Sign in',
    description: 'On the Reset Password screen a person enters the emailed OTP plus a new password, resends the code if needed, and lands on a success state with a Go-to-Login button.' },
  { surface: 'app', path: '/survey', label: 'Interests Survey', group: 'Sign in',
    description: 'On the interests Survey screen a brand-new member picks at least the minimum number of interest categories (grouped by super category) to unlock the app and personalise their feed.' },
  { surface: 'app', path: '/signup-referral', label: 'Referral Prompt', group: 'Sign in',
    description: 'On the Referral Prompt step (shown in-app only, right after a Google signup — no deep link) a new member enters or skips a friend\'s referral code before continuing to the survey.' },
  { surface: 'app', path: '/profile', label: 'Profile', group: 'Account',
    description: 'On the Profile screen a member edits their identity header, verifies their email (deep-linked with ?verifyEmail=1), manages links/pet panels and host/venue shortcuts, and posts to or browses their own posts grid.' },
  { surface: 'app', path: '/account', label: 'Profile Settings', group: 'Account',
    description: 'On the Profile Settings screen a member edits their account details, changes photo, sees completion and account-health meters, sets profile privacy, manages connected accounts, language and security, opens Communication Preferences, and logs out. Their @handle is assigned automatically and is shown, with the link that copies it, on their profile.' },
  { surface: 'app', path: '/account/health', label: 'Account Health', group: 'Account',
    description: 'On the Account Health screen a member reads their health score meter, the point-by-point breakdown and any admin remarks explaining the band.' },
  { surface: 'app', path: '/account/communication', label: 'Communication Preferences', group: 'Account',
    description: 'On the Communication Preferences screen (reached from one row in Profile Settings) a member sees Email, WhatsApp and SMS with where each one goes and whether authentication messages arrive there, and opens each channel screen from it.' },
  { surface: 'app', path: '/account/mail-preference', label: 'Mail Preference', group: 'Account',
    description: 'On the Mail Preference screen (reached from Profile Settings > Communication Preferences) a member switches individual email categories on or off, decides whether authentication messages may arrive by email, sees which emails always arrive, and unsubscribes from or resubscribes to everything at once.' },
  { surface: 'app', path: '/account/sms-preference', label: 'SMS Preference', group: 'Account',
    description: 'On the SMS Preference screen (reached from Profile Settings > Communication Preferences) a member decides whether authentication messages may reach them by text. They are the only texts Duncit sends today.' },
  { surface: 'app', path: '/verification', label: 'Verification', group: 'Account',
    description: 'On the Verification screen a member uploads an identity document (image or PDF), submits their structured address, and checks the status of their email verification.' },
  { surface: 'app', path: '/saved', label: 'Saved Items', group: 'Account',
    description: 'On the Saved Items screen a member reviews the pods they bookmarked, searches them server-side, and narrows the list with a Super > Category > Sub filter and a sort control.' },
  { surface: 'app', path: '/faqs', label: 'FAQs', group: 'Account',
    description: 'On the FAQs screen a member searches grouped questions and expands any accordion to read the answer.' },
  { surface: 'app', path: '/badges', label: 'Badges', group: 'Account',
    description: 'On the Badges screen a member sees every Duncit badge with its goal, the window that goal must happen in, and their own progress bar — earned ones read Achieved with the date and also show on their profile.' },
  { surface: 'app', path: '/tour-guide', label: 'Tour Guide', group: 'Account',
    description: 'On the Tour Guide screen a member sees every guided walkthrough available for their roles, whether each is completed, and restarts one — which navigates to that tour\'s screen or tab and begins the coach marks.' },
  { surface: 'app', path: '/pod-plans', label: 'Pod Plans', group: 'Account',
    description: 'On the Pod Plans screen a member currently sees a coming-soon placeholder for browsing plans ("Browse plans and pick what fits your vibe").' },
  { surface: 'app', path: '/policies', label: 'Policies', group: 'Account',
    description: 'On the Policies screen a member sees the list of published policy documents and taps one to open the reader.' },
  { surface: 'app', path: '/policies/:slug', label: 'Policy Reader', group: 'Account',
    description: 'On a Policy reader screen a member reads the full text of one policy document and downloads it as a PDF.' },
  { surface: 'app', path: '/duncit-coin', label: 'Duncit Coin', group: 'Account',
    description: 'On the Duncit Coin screen a member sees their loyalty coin balance and the full earn/spend ledger of every coin transaction.' },
  { surface: 'app', path: '/referral', label: 'Refer & Earn', group: 'Account',
    description: 'On the Refer & Earn screen a member copies their referral code, shares the invite link via the share sheet or WhatsApp, and tracks everyone who has joined with it and what it earned.' },
  { surface: 'app', path: '/leaderboard', label: 'Leaderboard', group: 'Account',
    description: 'On the Leaderboard screen a member switches between the Users, Hosts, Club Admins, Venues and Brands boards and the period toggle, sees their own standing and points, and reads how points are earned and what finishing well pays.' },
  { surface: 'app', path: '/membership', label: 'Membership', group: 'Account',
    description: 'On the Membership screen a member reads the announced tier cards, the full comparison table pulled from Admin, and submits the notify-me form — the purchase CTAs are deliberately disabled because membership is announced, not yet sold.' },
  { surface: 'app', path: '/pod-history', label: 'Pod History', group: 'Pods',
    description: 'On the Pod History screen a member reviews every pod they have joined, searches the list, and applies a Super > Category filter and a date/price sort before opening one booking.' },
  { surface: 'app', path: '/pod-history/:membershipId', label: 'Pod History Details', group: 'Pods',
    description: 'On a Pod History Details screen a member sees a booking\'s status and timeline, opens the pod, backs out (with the refund/deduction preview) or rejoins, downloads the ticket or invoice PDF, checks any product orders on that pod, and raises a support ticket.' },
  { surface: 'app', path: '/booking/:bookingId', label: 'Your Booking', group: 'Pods',
    description: 'On the Booking landing screen — the target of the payment-receipt email\'s "View Booking" button — the app resolves the booking server-side and immediately forwards the member to that pod\'s detail screen.' },
  { surface: 'app', path: '/previous-pods', label: 'Previous Pods', group: 'Pods',
    description: 'On the Previous Pods screen a member browses the full list of pods that have already taken place in their selected city/super-category, with the same category and price/date filters Home uses.' },
  { surface: 'app', path: '/happening-nearby', label: 'Happening Nearby', group: 'Pods',
    description: 'On the Happening Nearby screen a member browses every live upcoming pod for their selected city/super-category, filters by category, price and date, and opens any pod.' },
  { surface: 'app', path: '/club/:clubSlug/pod/:podSlug', label: 'Pod Details', group: 'Pods',
    description: 'On a Pod Details screen a member views the hero gallery, overview, schedule and venue map, saves/shares the pod, likes and comments on it, adds the pod\'s shop products, and books a seat (or joins a free pod) — plus backs out or keeps their spot if already joined.' },
  { surface: 'app', path: '/pod/:podId/feedback', label: 'Pod Feedback', group: 'Pods',
    description: 'On the Pod Feedback screen — behind the rating link a host shares — a guest rates the pod on each applicable aspect and leaves a message, with their earlier answers pre-loaded so a second visit edits rather than duplicates the rating.' },
  { surface: 'app', path: '/club/:clubSlug', label: 'Club Details', group: 'Pods',
    description: 'On a Club Details screen a member views the club\'s hero media, summary and category breadcrumbs, follows or unfollows it, shares it, and browses its members, moments and upcoming pods.' },
  { surface: 'app', path: '/chats/:podId', label: 'Chat Room', group: 'Pods',
    description: 'On a pod Chat Room a member reads history plus realtime messages, sends text or an image, reacts with emoji, opens the participants panel and any member\'s profile, and jumps to the pod — the composer locks once the pod has ended.' },
  { surface: 'app', path: '/checkout/:podId', label: 'Pod Checkout', group: 'Pods',
    description: 'On the Pod Checkout screen a member reviews the seat order summary, fills their contact details, applies a coupon and redeems Duncit Coins, then pays via Razorpay (or the dummy gateway in test mode) and downloads the ticket on success.' },
  { surface: 'app', path: '/gift-cards', label: 'Gift Cards', group: 'Account',
    description: 'On the Gift Cards screen a member buys a themed card (any category or the Pod Shop) for themselves or a friend and reviews the cards they hold or gifted (flag-gated by gift_cards).' },
  { surface: 'app', path: '/gift-cards/checkout', label: 'Gift Card Checkout', group: 'Account',
    description: 'On the Gift Card Checkout screen a member reviews the theme, amount and recipient, then pays; the card and its code are emailed on success.' },
  { surface: 'app', path: '/gift-cards/redeem', label: 'Redeem Gift Card', group: 'Account',
    description: 'On the Redeem Gift Card screen a member enters a code, checks the card, and converts its full value into Duncit Coins.' },
  { surface: 'app', path: '/gift-card/:code', label: 'Gift Card Claim', group: 'Account',
    description: 'On the Gift Card Claim screen — opened from a shared email or link — a member sees who sent the card, its value and expiry, and redeems it into Duncit Coins.' },
  { surface: 'app', path: '/pod-ideas', label: 'Pod Ideas', group: 'Pods',
    description: 'On the Pod Ideas board a member submits a new pod idea against a Super > Category > Sub cascade, searches and filters ideas by category and status, likes, shares and comments on other ideas, and deletes their own.' },
  { surface: 'app', path: '/hosts-venues', label: 'Hosts & Venues', group: 'Discover',
    description: 'On the Hosts & Venues discovery screen a member switches between the Hosts and Venues tabs, follows or unfollows a host, and opens a host\'s public profile or a venue\'s details.' },
  { surface: 'app', path: '/venues', label: 'Venues', group: 'Discover',
    description: 'On the Venues screen a member browses public venues in their selected location, filters with the super-category chip rail and a search box, and opens a venue\'s page.' },
  { surface: 'app', path: '/venue/:venueId', label: 'Venue Details', group: 'Discover',
    description: 'On a Venue Details screen a member views the venue\'s photos, full address, amenity and category chips, and the pods scheduled to happen there.' },
  { surface: 'app', path: '/u/:userId', label: 'Public Profile', group: 'Discover',
    description: 'On another member\'s Public Profile a member follows, withdraws a pending follow request or unfollows, views their badges and role chips, opens their posts, and taps through to their follower/following lists.' },
  { surface: 'app', path: '/post/:postId', label: 'Post Detail', group: 'Discover',
    description: 'On the Post Detail screen — the target of post-activity notifications — a member views a single post in the full viewer, likes and comments on it, and deletes it if it is their own.' },
  { surface: 'app', path: '/follow', label: 'Followers & Following', group: 'Discover',
    description: 'On the Followers/Following list screen (opened in-app by tapping a follow count on your own or someone\'s profile — no deep link registered) a member switches between the Followers and Following tabs, follows or unfollows anyone in the list, and opens their profile.' },
  { surface: 'app', path: '/shop', label: 'Pod Shop', group: 'Shop',
    description: 'On the Pod Shop screen a member browses the platform-wide catalogue of approved pod-available products with category chips, debounced search and name/price sorting, quick-adds an item to the cart, and opens any product.' },
  { surface: 'app', path: '/product/:productId', label: 'Product Detail', group: 'Shop',
    description: 'On a Product Detail screen a member views the product\'s images, description and variant options, and adds or removes it from the cart against the cheapest live pod that stocks it (browse-only when no pod does).' },
  { surface: 'app', path: '/cart', label: 'Cart', group: 'Shop',
    description: 'On the Cart screen a member reviews every product added from any Pod Shop grouped by pod, changes quantities, removes lines or clears the cart, and continues to product checkout.' },
  { surface: 'app', path: '/product-checkout', label: 'Product Checkout', group: 'Shop',
    description: 'On the Product Checkout screen a member picks a saved delivery address (or enters a new one), sees the live per-warehouse delivery quote, applies a coupon and redeems Duncit Coins, then pays for every cart line in one Razorpay product payment.' },
  { surface: 'app', path: '/orders', label: 'My Product Order History', group: 'Shop',
    description: 'On the Order History screen a member reviews every product order they have placed across all pods, newest first, each with its full fulfilment tracking.' },
  { surface: 'app', path: '/address-book', label: 'Address Book', group: 'Shop',
    description: 'On the Address Book screen a member adds, edits, deletes and sets the default among their saved delivery addresses.' },
  { surface: 'app', path: '/earn', label: 'Earn with Duncit', group: 'Earn',
    description: 'On the Earn with Duncit screen a member picks one of four earning journeys — hosting a pod, registering a venue, listing a product or managing a club — with a card disabled when they already hold that role or have a pending onboarding meeting, and follows the approved-role CTA into the studio or partner portal.' },
  { surface: 'app', path: '/become-host', label: 'Be a Host', group: 'Earn',
    description: 'On the Be a Host onboarding screen a member picks their hosting categories, answers the HOST onboarding survey and books the onboarding meeting that starts their host application.' },
  { surface: 'app', path: '/register-venue', label: 'Be a Venue Owner', group: 'Earn',
    description: 'On the Be a Venue Owner onboarding screen a member picks categories, completes the VENUE survey and requests the onboarding meeting to list their space as a Duncit venue.' },
  { surface: 'app', path: '/survey/ecomm', label: 'List Your Product', group: 'Earn',
    description: 'On the List Your Product onboarding screen (reached in-app from Earn — no deep link registered) a member picks categories, completes the ECOMM survey and requests the onboarding meeting to start selling products to the Duncit community.' },
  { surface: 'app', path: '/be-club-admin', label: 'Be a Club Admin', group: 'Earn',
    description: 'On the Be a Club Admin onboarding screen a member picks categories, completes the CLUB_ADMIN survey and requests the onboarding meeting to run a Duncit club and manage its pods and members.' },
  { surface: 'app', path: '/host/manage', label: 'Host Studio', group: 'Host Menu',
    description: 'In Host Studio a host starts a new pod, resumes or deletes an in-progress draft (with the retention-day warning), reviews their approved host categories and the apply-for-more banner, manages their live pods, and shares payout/completion actions.' },
  { surface: 'app', path: '/host/dashboard', label: 'Host Dashboard', group: 'Host Menu',
    description: 'On the Host Dashboard a host reads their earnings summary tiles, pod/booking stat cards, health band and insights, and jumps straight to Create Pod, Your Pods, Verification or Wallet.' },
  { surface: 'app', path: '/host/apply', label: 'Apply to Host', group: 'Host Menu',
    description: 'On the Apply Now screen an existing host applies to host in a new category by picking the category, completing that category\'s survey and submitting the request.' },
  { surface: 'app', path: '/create-pod', label: 'Create Pod', group: 'Host Menu',
    description: 'On the Create Pod screen a host walks the multi-step stepper — details, category, club, schedule, venue slot, pricing, products and media — with the draft autosaving, then publishes the pod (landing on Host Studio, or on the pending screen if the venue slot needs approval).' },
  { surface: 'app', path: '/host/pod-pending/:podId', label: 'Pod Pending Approval', group: 'Host Menu',
    description: 'On the Pod Pending screen a host who just created a pod sees the waiting banner, the pod summary, the venue\'s contact card with its slot-request status, and the club-admin help card while the slot request is approved.' },
  { surface: 'app', path: '/host/wallet', label: 'Wallet / Withdrawal', group: 'Host Menu',
    description: 'On the Wallet screen a partner (host, venue owner, e-commerce manager or club admin) checks their earned balance, reads the credit/debit transaction history and past withdrawal requests with their payout cycle, and raises a new withdrawal.' },
  { surface: 'app', path: '/venues/manage', label: 'Venue Studio', group: 'Venue Menu',
    description: 'In Venue Studio a venue owner reviews their venue count, approved venues and total capacity, the monthly bookings chart, and the list of pods booked into their spaces.' },
  { surface: 'app', path: '/venues/slot-requests', label: 'Slot Requests', group: 'Venue Menu',
    description: 'On the Slot Requests screen (reached in-app from the Venue menu — no deep link registered) a venue owner works the queue of pending booking requests per venue, reads each requested window (including whole-day and multi-day slots), and approves or declines it so the pod can go live.' },
  { surface: 'app', path: '/venues/earnings', label: 'Venue Earnings', group: 'Venue Menu',
    description: 'On the Venue Earnings screen a venue owner reads their earnings summary tiles and each payout card with its slot-price-minus-commission waterfall and PENDING/APPROVED/REJECTED status.' },
  { surface: 'app', path: '/venues/:venueId/health', label: 'Venue Health', group: 'Venue Menu',
    description: 'On the Venue Health screen a venue owner reads that venue\'s health score meter, the point-by-point breakdown and any admin remarks.' },
  { surface: 'app', path: '/products/manage', label: 'E-commerce Studio', group: 'E-commerce Menu',
    description: 'In the E-commerce Studio an e-commerce manager reviews their catalogue stats — product count, total stock and average price — plus the stock-by-product chart (or a not-available notice when product features are switched off).' },
  { surface: 'app', path: '/clubs/manage', label: 'Club Studio', group: 'Club Admin Menu',
    description: 'In Club Studio a club admin reviews every pod across the clubs they administer, with the same figures strip and pod rows Venue Studio shows for its bookings.' },
  { surface: 'app', path: '/support', label: 'Support', group: 'Support',
    description: 'On the Support help center a member searches the FAQ knowledge base, reads the top FAQs and topic list, starts a conversation with an agent, and reaches every other support tool (SOS, callback, tickets, feedback, grievance).' },
  { surface: 'app', path: '/support/sos', label: 'SOS', group: 'Support',
    description: 'On the SOS screen a member picks the live pod they are attending, adds a note and fires an emergency SOS to the Duncit safety team, then watches the active SOS status.' },
  { surface: 'app', path: '/support/callback', label: 'Request a Callback', group: 'Support',
    description: 'On the Callback screen a member dials the configured support number directly, or submits a callback request with a reason and reviews their past callback requests.' },
  { surface: 'app', path: '/support/chat', label: 'Chat with Us', group: 'Support',
    description: 'On the Chat with Us screen a member taps the single "Chat live with an agent" card to open the real-time support chat.' },
  { surface: 'app', path: '/live-chat', label: 'Live Chat', group: 'Support',
    description: 'On the Live Chat screen a member converses in real time with AI-first support and human agents — sending messages and file attachments, seeing typing and read receipts, resolving or reopening the chat, leaving feedback and emailing themselves the transcript.' },
  { surface: 'app', path: '/support/all', label: 'All Support Tickets', group: 'Support',
    description: 'On the All Support Tickets screen a member sees one combined list of every support request they have raised — SOS, callbacks, support tickets and chats — with prefixed ticket numbers, and opens a ticket thread or the live chat.' },
  { surface: 'app', path: '/support/tickets', label: 'Create Support Ticket', group: 'Support',
    description: 'On the Create Support Tickets screen a member raises a new ticket (optionally pre-scoped to a pod) with subject, category and description, and jumps to FAQs if the answer might already exist.' },
  { surface: 'app', path: '/tickets/:ticketId', label: 'Ticket Details', group: 'Support',
    description: 'On a Ticket Details screen a member reads one ticket\'s subject, status and full reply thread, posts a reply with attachments, resolves or reopens it with a reason, leaves feedback and emails the transcript.' },
  { surface: 'app', path: '/support/feedback', label: 'Report a Problem', group: 'Support',
    description: 'On the Report a Problem screen a member sends the team a categorised feedback note with optional media, which lands instantly in Duncit\'s Slack.' },
  { surface: 'app', path: '/support/grievance', label: 'Raise a Grievance', group: 'Support',
    description: 'On the Grievance screen a member files a formal grievance and receives a reference number on screen (and by email) to quote when chasing it, alongside the grievance officer\'s contact card.' },
  // The catch-all 404 route is deliberately not listed: it is not somewhere to
  // be sent, and a bot that could answer "go to Not Found" would.
];
