/**
 * Write `docs/email-catalogue.md` from the catalogue.
 *
 *   npm run docs:emails
 *
 * A generated reading copy rather than a hand-kept list, for the reason every
 * hand-kept list in this repo eventually earns a generator: the moment somebody
 * adds a template and forgets the table, the table becomes the thing people
 * stop trusting. The catalogue is the source; this only reads it.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { EMAIL_CATALOGUE } from '@services/email/catalogue';
import { TEMPLATE_CATEGORIES } from '@services/email/template-categories';
import { WA_EVENT_BY_KEY } from '@modules/platform/whatsapp/whatsapp.events';

const OUT = join(__dirname, '..', '..', 'docs', 'email-catalogue.md');

/** Reading order: the member first, then each partner kind, then staff. */
const AUDIENCE_ORDER = ['USER', 'HOST', 'VENUE', 'ECOMM', 'CLUB_ADMIN', 'SUPPORT', 'ADMIN', 'PUBLIC'];

const escape = (text: string) => text.replaceAll('|', String.raw`\|`);

const rows = [...EMAIL_CATALOGUE].sort((a, b) => {
  const byAudience = AUDIENCE_ORDER.indexOf(a.audience) - AUDIENCE_ORDER.indexOf(b.audience);
  return byAudience === 0 ? a.slug.localeCompare(b.slug) : byAudience;
});

/**
 * A `waEvent` this database's WhatsApp catalogue does not have is reported in
 * the table rather than quietly printed: `check:emails` fails the build on it,
 * and the doc saying so is what makes the failure make sense.
 */
function twin(waEvent?: string): string {
  if (!waEvent) return '—';
  return WA_EVENT_BY_KEY.has(waEvent) ? `\`${waEvent}\`` : `${waEvent} (UNKNOWN)`;
}

const body = rows
  .map((row) =>
    [
      '',
      row.audience,
      escape(row.name),
      `\`${row.slug}\``,
      escape(row.fires),
      TEMPLATE_CATEGORIES[row.slug] ?? '(none)',
      row.mjml ? 'code' : 'disk',
      twin(row.waEvent),
      row.vars.map((variable) => `\`${variable.key}\``).join(', '),
      '',
    ].join(' | ').trim()
  )
  .join('\n');

const file = `# Duncit email catalogue

Every email the product sends: who it is written for, what makes it fire, which
header/footer fragment wraps it, and the variables it fills.

GENERATED by \`npm run docs:emails\` from \`server/src/services/email/catalogue\`
— the catalogue is the source, this is the reading copy. ${rows.length} templates.

- **Fragment** — the header/footer fragment that wraps the body, edited in
  Tech > Emails > Fragments. Written onto every stored row by
  \`npm run migrate:email-chrome\`.
- **Body** — \`disk\` means the MJML is an on-disk \`.mjml\` file, \`code\` means the
  catalogue builds it (CLAUDE.md rule 28: no new local MJML files).
- **WhatsApp twin** — the \`WA_EVENTS\` key this email goes out beside, off the
  same array of values, through \`notifyEvent\`. \`—\` means it is sent on its own.
- Every template also receives the chrome variables \`brand_logo_url\`,
  \`app_name\`, \`app_url\`, \`website_url\`, \`support_email\`, \`year\`,
  \`unsubscribe_url\` and \`footer_note\` on every send.

| Audience | Email | Slug | Fires when | Fragment | Body | WhatsApp twin | Variables |
| --- | --- | --- | --- | --- | --- | --- | --- |
${body}

## Known gaps

| Slug | Gap |
| --- | --- |
| \`club-admin-host-help\` | Nothing in the server fires \`CLUB_ADMIN_HOST_HELP\`. The scenario is in the WhatsApp catalogue and neither channel has ever sent it — the "ask my club admin for help" action does not reach the server. |
| \`club-admin-venue-help\` | Same, for \`CLUB_ADMIN_VENUE_HELP\`. |
| \`payment-release-approved\` | Superseded by \`payout-statement\`, which is what \`paymentRelease.notifyApproval\` actually sends. Kept so an existing row is not orphaned. |
| \`meeting-booked\`, \`meeting-scheduled\`, \`meeting-approved\`, \`meeting-rejected\` | Superseded by the sixteen per-party \`<party>-onboarding-*\` templates. Kept so existing rows and their admin edits are not orphaned. |
`;

writeFileSync(OUT, file, 'utf8');
console.log(`docs:emails — wrote ${rows.length} row(s) to docs/email-catalogue.md`);
