import { apply } from "./e.mjs";

// ---- schema factory
apply("packages/coupons/src/coupon/coupon.form.ts", [
  [
    "import { z } from 'zod';\n\nconst CODE_PATTERN",
    "import { z } from 'zod';\n\n/** The translator a schema reads its messages from (rule 38). */\nexport type CouponTranslate = (key: string) => string;\n\nconst CODE_PATTERN",
  ],
  [
    "/** Empty string / null -> null, otherwise a positive integer. */\nconst optionalPositiveInt = z\n  .union([z.literal(''), z.null(), z.coerce.number()])\n  .transform((value) => (value === '' || value === null ? null : value))\n  .refine((value) => value === null || Number.isInteger(value), 'Must be a whole number')\n  .refine((value) => value === null || value >= 1, 'Must be at least 1');\n\nexport const couponFormSchema: z.ZodType<CouponFormValues, z.ZodTypeDef, unknown> = z\n  .object({\n    code: z\n      .string()\n      .trim()\n      .transform((value) => value.toUpperCase())\n      .refine((value) => CODE_PATTERN.test(value), 'Code must be 3-30 chars: A-Z, 0-9, - or _'),\n    description: z.string().trim().max(300).default(''),\n    discount_pct: z.coerce\n      .number({ invalid_type_error: 'Discount must be a number' })\n      .min(1, 'Minimum 1%')\n      .max(100, 'Maximum 100%'),\n    scope: z.enum(['GLOBAL', 'POD']),\n    pod_id: z.string().trim().default(''),\n    valid_from: z.string().trim().default(''),\n    valid_until: z.string().trim().default(''),\n    max_uses: optionalPositiveInt,\n    per_user_limit: optionalPositiveInt,\n    min_order_amount: z.coerce\n      .number({ invalid_type_error: 'Must be a number' })\n      .min(0, 'Must be 0 or greater')\n      .default(0),\n    is_active: z.boolean().default(true),\n  })\n  .superRefine((values, ctx) => {\n    if (values.scope === 'POD' && !values.pod_id) {\n      ctx.addIssue({\n        code: z.ZodIssueCode.custom,\n        path: ['pod_id'],\n        message: 'Pick a pod for a pod-scoped coupon',\n      });\n    }\n  });",
    "/** Empty string / null -> null, otherwise a positive integer. */\nconst optionalPositiveInt = (t: CouponTranslate) =>\n  z\n    .union([z.literal(''), z.null(), z.coerce.number()])\n    .transform((value) => (value === '' || value === null ? null : value))\n    .refine((value) => value === null || Number.isInteger(value), t('shell.coupons.wholeNumber'))\n    .refine((value) => value === null || value >= 1, t('shell.coupons.atLeastOne'));\n\n/**\n * Built from the console's translator rather than exported ready-made: a\n * validation message is copy the admin reads, so it follows their language like\n * every other string on the screen (rule 38).\n */\nexport const buildCouponFormSchema = (\n  t: CouponTranslate,\n): z.ZodType<CouponFormValues, z.ZodTypeDef, unknown> =>\n  z\n    .object({\n      code: z\n        .string()\n        .trim()\n        .transform((value) => value.toUpperCase())\n        .refine((value) => CODE_PATTERN.test(value), t('shell.coupons.codeInvalid')),\n      description: z.string().trim().max(300).default(''),\n      discount_pct: z.coerce\n        .number({ invalid_type_error: t('shell.coupons.discountNumber') })\n        .min(1, t('shell.coupons.discountMin'))\n        .max(100, t('shell.coupons.discountMax')),\n      scope: z.enum(['GLOBAL', 'POD']),\n      pod_id: z.string().trim().default(''),\n      valid_from: z.string().trim().default(''),\n      valid_until: z.string().trim().default(''),\n      max_uses: optionalPositiveInt(t),\n      per_user_limit: optionalPositiveInt(t),\n      min_order_amount: z.coerce\n        .number({ invalid_type_error: t('shell.coupons.amountNumber') })\n        .min(0, t('shell.coupons.amountMin'))\n        .default(0),\n      is_active: z.boolean().default(true),\n    })\n    .superRefine((values, ctx) => {\n      if (values.scope === 'POD' && !values.pod_id) {\n        ctx.addIssue({\n          code: z.ZodIssueCode.custom,\n          path: ['pod_id'],\n          message: t('shell.coupons.podRequired'),\n        });\n      }\n    });",
  ],
  [
    "/** Map the form values to the GraphQL CreateCouponInput / UpdateCouponInput. */\nexport function toCouponInput(values: CouponFormValues) {\n  const cast = couponFormSchema.parse(values);",
    "/**\n * Map the form values to the GraphQL CreateCouponInput / UpdateCouponInput.\n *\n * Runs the schema again for its coercions and defaults, never for its messages\n * — the form has already blocked anything invalid — so the key itself is a fine\n * stand-in for a translator here.\n */\nexport function toCouponInput(values: CouponFormValues) {\n  const cast = buildCouponFormSchema((key) => key).parse(values);",
  ],
]);
