import { apply } from "./e.mjs";

// ---- ad-request.types.ts: schema messages from the catalogue
apply("packages/ad-request-form/src/ad-request.types.ts", [
  [
    "import { AD_MEDIA_TYPE_VALUES, AD_POSITION_VALUES, type AdMediaType, type AdPosition } from './ad-options';",
    "import { AD_MEDIA_TYPE_VALUES, AD_POSITION_VALUES, type AdMediaType, type AdPosition } from './ad-options';\nimport type { Translate } from './i18n/useTranslation';",
  ],
  [
    "/** Ad request contract — RHF + Zod. Mirrors the server SubmitAdRequestInput rules. */\nexport const adRequestSchema = z.object({\n  ad_title: requiredText('Ad title', 3, 120),\n  ad_description: requiredText('Ad description', 10, 1000),\n  ad_type: z.enum(AD_MEDIA_TYPE_VALUES, { required_error: 'Ad type is required' }),\n  media_url: z.string().trim().min(1, 'Upload the ad media'),\n  position: z.enum(AD_POSITION_VALUES, { required_error: 'Ad position is required' }),\n  start_at: z\n    .string()\n    .trim()\n    .min(1, 'Ad start date is required')\n    .refine((value) => !Number.isNaN(new Date(value).getTime()), 'Ad start date must be a valid date')\n    .refine(isTodayOrLater, 'Ad start date must be today or later'),\n  duration_days: z\n    .number({ invalid_type_error: 'Ad duration must be a number of days' })\n    .int('Ad duration must be whole days')\n    .min(1, 'Ad duration must be at least 1 day'),\n  redirect_url: z\n    .string()\n    .trim()\n    .default('')\n    .refine(isHttpUrl, 'Redirect URL must be a valid http(s) link'),\n  target_audience: optionalText('Target audience', 500, { defaultEmpty: true }),\n});\n\nexport type AdRequestFormValues = z.infer<typeof adRequestSchema>;",
    "/**\n * Ad request contract — RHF + Zod. Mirrors the server SubmitAdRequestInput\n * rules.\n *\n * Built from the caller's translator: a validation message is copy the\n * advertiser reads, so it follows their language like every other string on\n * the screen (rule 38). The field NAMES handed to `requiredText`/`optionalText`\n * come from the same catalogue rows the labels do.\n */\nexport const buildAdRequestSchema = (t: Translate) =>\n  z.object({\n    ad_title: requiredText(t('adRequest.form.title'), 3, 120),\n    ad_description: requiredText(t('adRequest.form.description'), 10, 1000),\n    ad_type: z.enum(AD_MEDIA_TYPE_VALUES, { required_error: t('adRequest.errors.typeRequired') }),\n    media_url: z.string().trim().min(1, t('adRequest.errors.mediaRequired')),\n    position: z.enum(AD_POSITION_VALUES, {\n      required_error: t('adRequest.errors.positionRequired'),\n    }),\n    start_at: z\n      .string()\n      .trim()\n      .min(1, t('adRequest.errors.startRequired'))\n      .refine(\n        (value) => !Number.isNaN(new Date(value).getTime()),\n        t('adRequest.errors.startInvalid'),\n      )\n      .refine(isTodayOrLater, t('adRequest.errors.startPast')),\n    duration_days: z\n      .number({ invalid_type_error: t('adRequest.errors.durationNumber') })\n      .int(t('adRequest.errors.durationWhole'))\n      .min(1, t('adRequest.errors.durationMin')),\n    redirect_url: z\n      .string()\n      .trim()\n      .default('')\n      .refine(isHttpUrl, t('adRequest.errors.redirectInvalid')),\n    target_audience: optionalText(t('adRequest.form.targetAudience'), 500, { defaultEmpty: true }),\n  });\n\nexport type AdRequestFormValues = z.infer<ReturnType<typeof buildAdRequestSchema>>;",
  ],
  [
    "export function makeAdRequestSchema(window: { min: number; max: number }) {\n  const max = Math.max(window.min, window.max);\n  return adRequestSchema.refine((values) => values.duration_days <= max, {\n    message: `Ad duration can be at most ${max} ${max === 1 ? 'day' : 'days'}`,\n    path: ['duration_days'],\n  });\n}",
    "export function makeAdRequestSchema(window: { min: number; max: number }, t: Translate) {\n  const max = Math.max(window.min, window.max);\n  return buildAdRequestSchema(t).refine((values) => values.duration_days <= max, {\n    message: t('adRequest.errors.durationMax', {\n      vars: { max: t('adRequest.days', { count: max, vars: { count: max } }) },\n    }),\n    path: ['duration_days'],\n  });\n}",
  ],
  [
    "/** Validates and maps the form values to the mutation input (empty optionals dropped). */\nexport function toSubmitAdRequestInput(values: AdRequestFormValues): SubmitAdRequestInput {\n  const cast = adRequestSchema.parse(values);",
    "/**\n * Validates and maps the form values to the mutation input (empty optionals\n * dropped).\n *\n * Runs the schema again for its coercions and defaults, never for its messages\n * — the form has already blocked anything invalid — so the key itself is a fine\n * stand-in for a translator here.\n */\nexport function toSubmitAdRequestInput(values: AdRequestFormValues): SubmitAdRequestInput {\n  const cast = buildAdRequestSchema(((key: string) => key) as Translate).parse(values);",
  ],
]);
