import { describeEmail, v, type EmailDef, type EmailVar } from './catalogue.types';

/**
 * The templates that already shipped — metadata only, no body.
 *
 * Their MJML is an on-disk `.mjml` file (or, for the eight account-status ones,
 * `emailTemplate.defaults.ts`), and that stays the source of the body: seeding
 * a second copy from here would silently replace whatever an admin last saved
 * in the editor. What these rows add is the part that never existed anywhere —
 * WHO the email is for, WHAT makes it fire, and WHICH variables it fills.
 *
 * That last one is the reason this file exists at all. `EmailTemplate.variables`
 * has been an empty array on every stored template since the collection was
 * created: `loadTemplate` fills it by regex-scanning the MJML for `{{ }}`, which
 * finds the names and nothing else — no description, no sample — so the Tech
 * portal's variable panel showed a bare list and the editor's preview rendered
 * every value blank. `migrate:email-chrome` writes these onto the stored rows.
 *
 * Category and footer sentence stay in `template-categories.ts`, which is where
 * they already were and where the migration already reads them.
 */

/** Four one-time-code emails carry the same three values. */
const otpVars = (purpose: string): readonly EmailVar[] => [
  v('name', 'The account holder’s first name.', 'Aarav'),
  v('otp', `The one-time code for ${purpose}.`, '482913'),
  v('expiresMinutes', 'How many minutes the code stays valid.', '10'),
];

/** The four host-request emails all render the same request. */
const HOST_REQUEST_VARS: readonly EmailVar[] = [
  v('host_name', 'The applicant’s name, as given on the request.', 'Meera Nair'),
  v('request_no', 'The request’s reference.', 'HR-000117'),
  v('category_path', 'The category being applied for, full path.', 'Sports › Racket › Badminton'),
  v('reviewer_notes', 'The reviewer’s note. Blank while the request is still open.', 'Approved — welcome aboard.'),
];

/** The onboarding-meeting emails share a core; only the extras differ. */
const meetingVars = (extra: readonly EmailVar[] = []): readonly EmailVar[] => [
  v('name', 'The applicant’s first name.', 'Meera'),
  v('kind', 'Which onboarding this is — Host, Venue, E-Commerce Brand or Club Admin.', 'Venue'),
  v('slot', 'The meeting slot, already formatted.', '26 Aug 2026, 4:30 PM'),
  ...extra,
];

const MEETING_LINK = v('link', 'The video-call link for the meeting.', 'https://meet.google.com/abc-defg-hij');
const MEETING_NOTES = v('notes', 'Anything staff added for the applicant. May be blank.', 'Please keep your GST certificate handy.');

/** The account/listing status pair: eight templates, four value shapes. */
const statusVars = (nameVar: string, nameDesc: string, valueVar: string, valueDesc: string, sampleName: string, sampleValue: string): readonly EmailVar[] => [
  v(nameVar, nameDesc, sampleName),
  v(valueVar, valueDesc, sampleValue),
  v('status', 'The new state, as a word — `active` or `deactivated`.', 'deactivated'),
];

export const EXISTING_EMAILS: readonly EmailDef[] = [
  // --- Sign-up, account and one-time codes -------------------------------
  describeEmail({
    slug: 'welcome',
    name: 'Welcome',
    description: 'A new account, whichever door it signed up through.',
    audience: 'USER',
    category: 'transactional',
    fires: 'An account is created — email signup, Google signup or the admin form',
    subject: 'Welcome to Duncit 🎉',
    footerNote: '',
    vars: [v('name', 'The new member’s first name.', 'Aarav')],
  }),
  describeEmail({
    slug: 'policy-acceptance',
    name: 'Policy Acceptance',
    description: 'The signup receipt for what the account holder agreed to.',
    audience: 'USER',
    category: 'legal',
    fires: 'An account is created and its policy acceptances are recorded',
    subject: 'Your Duncit policy acceptance',
    footerNote: '',
    vars: [
      v('name', 'The new member’s first name.', 'Aarav'),
      v('policies', 'The accepted policy titles, joined by the service.', 'Terms of Use, Privacy Policy'),
      v('policies_url', 'Where to read them again.', 'https://duncit.com/legal'),
    ],
  }),
  describeEmail({
    slug: 'policy-updated',
    name: 'Policy Updated',
    description: 'Everyone who accepted a policy, when Legal publishes new wording for it.',
    audience: 'USER',
    category: 'legal',
    fires: 'Legal publishes a new version of a policy that has acceptances',
    subject: 'We’ve updated the {{policy_title}}',
    footerNote: '',
    vars: [
      v('name', 'The account holder’s first name.', 'Aarav'),
      v('policy_title', 'The policy that changed.', 'Privacy Policy'),
      v('summary', 'Legal’s own note on what changed. May be blank.', 'We now name our analytics processors.'),
      v('policy_url', 'Where to read the new version.', 'https://duncit.com/legal/privacy-policy'),
      v('updated_at', 'When it was published, already formatted.', '23 Aug 2026'),
    ],
  }),
  describeEmail({
    slug: 'unsubscribe-confirmed',
    name: 'Unsubscribe Confirmed',
    description: 'Confirms an opt-out to the person who made it. Transactional, so it arrives regardless.',
    audience: 'USER',
    category: 'transactional',
    fires: 'Someone changes their mail preferences or uses a one-click unsubscribe',
    subject: 'Your Duncit email preferences were updated',
    footerNote: '',
    vars: [v('email', 'The address whose preferences changed.', 'aarav@example.com')],
  }),
  describeEmail({
    slug: 'email-verification-otp',
    name: 'Email Verification OTP',
    description: 'The code that verifies an address at signup or when it is changed.',
    audience: 'USER',
    category: 'authentication',
    fires: 'An address needs verifying',
    subject: 'Verify your Duncit email',
    footerNote: '',
    vars: otpVars('verifying this address'),
  }),
  describeEmail({
    slug: 'password-reset-otp',
    name: 'Password Reset OTP',
    description: 'The code that starts a password reset. The confirmation afterwards is `password-changed`.',
    audience: 'USER',
    category: 'authentication',
    fires: 'Someone asks to reset their password',
    subject: 'Reset your Duncit password',
    footerNote: '',
    vars: otpVars('resetting the password'),
  }),
  describeEmail({
    slug: 'password-change-otp',
    name: 'Password Change OTP',
    description: 'The code that confirms a password change from inside the account.',
    audience: 'USER',
    category: 'authentication',
    fires: 'A signed-in account changes its password',
    subject: 'Confirm your Duncit password change',
    footerNote: '',
    vars: otpVars('confirming the change'),
  }),
  describeEmail({
    slug: 'account-deletion-otp',
    name: 'Account Deletion OTP',
    description: 'The code that confirms an account deletion.',
    audience: 'USER',
    category: 'authentication',
    fires: 'An account asks to be deleted',
    subject: 'Confirm your Duncit account deletion',
    footerNote: '',
    vars: otpVars('confirming the deletion'),
  }),
  describeEmail({
    slug: 'login-otp',
    name: 'Login OTP',
    description:
      'The passwordless sign-in code for the consumer apps. The email half of Continue with OTP — the phone half goes over WhatsApp and never through here.',
    audience: 'USER',
    category: 'authentication',
    fires: 'Somebody asks to sign in to mWeb or the app with a one-time code',
    subject: 'Your Duncit sign-in code',
    footerNote: '',
    vars: otpVars('signing in'),
  }),
  describeEmail({
    slug: 'portal-login-otp',
    name: 'Portal Login OTP',
    description: 'The passwordless sign-in code for a console. Names the portal, since a code only works for the one it was asked from.',
    audience: 'ADMIN',
    category: 'authentication',
    fires: 'Somebody asks to sign in to a Duncit console',
    subject: 'Your Duncit sign-in code',
    footerNote: '',
    vars: [
      ...otpVars('signing in'),
      v('portal', 'Which console the code is for.', 'Finance'),
    ],
  }),

  // --- Bookings and pods --------------------------------------------------
  describeEmail({
    slug: 'event-ticket',
    name: 'Pod Ticket',
    description: 'The booking confirmation, with the ticket PDF attached. The only booking email a free join gets.',
    audience: 'USER',
    category: 'transactional',
    fires: 'A booking is confirmed — paid, or a free join',
    subject: 'Your ticket — {{event_title}}',
    footerNote: '',
    vars: [
      v('name', 'The member’s first name.', 'Aarav'),
      v('event_title', 'The pod’s title.', 'Sunday Badminton Doubles'),
      v('date_label', 'When it runs, already formatted.', 'Sun, 24 Aug 2026, 7:00 AM'),
      v('venue_line', 'The venue and address, or the meeting platform for a virtual pod.', 'Sector 62 Sports Arena, Noida'),
      v('ticket_code', 'The code scanned at the door.', 'DUN-TKT-9F3A21'),
      v('seats_count', 'How many people this one ticket admits.', '2'),
      v('booking_url', 'Deep link to the booking.', 'https://duncit.com/bookings/DUN-MEM-5512'),
      v('app_url', 'Alias of `booking_url`, kept for templates cached before the rename.', 'https://duncit.com/bookings/DUN-MEM-5512'),
    ],
  }),
  describeEmail({
    slug: 'payment-receipt',
    name: 'Payment Receipt',
    description: 'The receipt for a successful payment, with the invoice PDF attached.',
    audience: 'USER',
    category: 'billing',
    fires: 'A payment is finalized as SUCCESS',
    subject: 'Payment Receipt — {{invoice_no}}',
    footerNote: '',
    vars: [
      v('name', 'Who paid.', 'Aarav Sharma'),
      v('summary', 'What was paid for — the pod and its time, or the payment’s description.', 'Sunday Badminton Doubles — 24/8/2026, 7:00:00 am'),
      v('invoice_no', 'The invoice reference.', 'DUN-INV-2026-000412'),
      v('payment_id', 'The gateway payment id.', 'pay_QK2f81ZzX9'),
      v('amount', 'The total, pre-formatted with its currency.', '₹450.00'),
      v('booking_url', 'Deep link to the booking.', 'https://duncit.com/bookings/DUN-MEM-5512'),
      v('app_url', 'Alias of `booking_url`, kept for templates cached before the rename.', 'https://duncit.com/bookings/DUN-MEM-5512'),
    ],
  }),
  describeEmail({
    slug: 'attendance-marked',
    name: 'Attendance Marked',
    description: 'The attendee’s own written record of a mark the host is paid on.',
    audience: 'USER',
    category: 'notification',
    fires: 'A door scan, a host’s manual mark, a Club Admin override or an admin check-in records someone present',
    subject: 'Attendance marked — {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The attendee’s first name.', 'Aarav'),
      v('pod_title', 'The pod they were marked at.', 'Sunday Badminton Doubles'),
      v('marked_at', 'When the mark was made, already formatted.', 'Sun, 24 Aug 2026, 7:04 AM'),
      v('place_line', 'Where the pod ran.', 'Sector 62 Sports Arena, Noida'),
      v('ticket_code', 'The ticket that was marked.', 'DUN-TKT-9F3A21'),
      v('seats_count', 'How many seats that ticket covers.', '2'),
      v('booking_url', 'Deep link to the booking, to contest a wrong mark.', 'https://duncit.com/bookings/DUN-MEM-5512'),
    ],
  }),
  describeEmail({
    slug: 'pod-updated',
    name: 'Pod Updated',
    description: 'Everyone who joined a pod, when its time or details change.',
    audience: 'USER',
    category: 'notification',
    fires: 'A published pod’s schedule or details are edited',
    subject: 'Pod updated — {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The member’s first name.', 'Aarav'),
      v('pod_title', 'The pod’s title.', 'Sunday Badminton Doubles'),
      v('when', 'The new time, already formatted.', 'Sun, 24 Aug 2026, 8:00 AM'),
    ],
  }),
  describeEmail({
    slug: 'pod-cancelled',
    name: 'Pod Cancelled (generic)',
    description:
      'Superseded by the three who-cancelled variants — `user-pod-cancelled-by-host`/`-venue`/`-duncit` — which name who cancelled and carry the refund figure and how long it takes. Kept so an existing row and its edits are not orphaned.',
    audience: 'USER',
    category: 'notification',
    fires: 'Nothing sends this any more — the who-cancelled variant does',
    subject: 'Pod cancelled — {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The member’s first name.', 'Aarav'),
      v('pod_title', 'The pod’s title.', 'Sunday Badminton Doubles'),
      v('when', 'When it was due to run, already formatted.', 'Sun, 24 Aug 2026, 7:00 AM'),
      v('reason', 'Why it was cancelled.', 'The venue withdrew the slot.'),
      v('refund_line', 'The refund sentence. Blank for a free booking.', 'Your payment of ₹450 will be refunded.'),
    ],
  }),
  describeEmail({
    slug: 'pod-refund',
    name: 'Pod Refund',
    description: 'The member, when a pod payment is marked for refund.',
    audience: 'USER',
    category: 'billing',
    fires: 'A pod payment is moved to REFUNDED',
    subject: 'Refund initiated — {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The member’s first name.', 'Aarav'),
      v('pod_title', 'The pod the refund is for.', 'Sunday Badminton Doubles'),
      v('amount', 'The refund, pre-formatted with its currency.', '₹450'),
      v('reason', 'Why it is being refunded.', 'Pod cancelled by the venue'),
    ],
  }),
  describeEmail({
    slug: 'pod-backout-spot-filled',
    name: 'Replacement Found',
    description: 'The member who backed out, when a replacement books their seat and the refund starts.',
    audience: 'USER',
    category: 'notification',
    fires: 'A backed-out spot is filled by another member',
    subject: 'Your spot was filled — {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The member’s first name.', 'Aarav'),
      v('pod_title', 'The pod they backed out of.', 'Sunday Badminton Doubles'),
      v('refund_line', 'The refund sentence. Blank for a free booking.', 'Your refund of ₹450 will be processed in 5-7 working days.'),
    ],
  }),
  describeEmail({
    slug: 'gift-card-received',
    name: 'Gift Card Received',
    description: 'The recipient of a gift card. The code in it IS the value somebody paid for, so it is transactional and cannot be opted out of.',
    audience: 'USER',
    category: 'transactional',
    fires: 'A gift card is bought for this address',
    subject: '{{sender_name}} sent you a Duncit gift card 🎁',
    footerNote: '',
    vars: [
      v('recipient_name', 'Who the card is for.', 'Aarav'),
      v('sender_name', 'Who sent it.', 'Meera'),
      v('amount', 'The face value, pre-formatted.', '₹500.00'),
      v('scope_label', 'What it can be spent on.', 'Pod Shop'),
      v('code', 'The bearer code that redeems it.', 'DUNGC-4TQX-91MB'),
      v('message_line', 'The sender’s personal note. Rendered verbatim, may be blank.', 'Happy birthday!'),
      v('redeem_url', 'Deep link to redeem it into Duncit Coins.', 'https://duncit.com/gift-cards/redeem'),
      v('expires_on', 'When it stops being redeemable.', '23 Aug 2027'),
    ],
  }),

  // --- Money out ----------------------------------------------------------
  describeEmail({
    slug: 'payout-statement',
    name: 'Payout Statement',
    description: 'The partner’s payout statement, with the PDF attached. Sent for pod releases AND for product invoices.',
    audience: 'HOST',
    category: 'billing',
    fires: 'A payment release is approved, or a product invoice is raised',
    subject: 'Payout approved · {{pod_title}}',
    footerNote: '',
    vars: [
      v('name', 'The beneficiary’s name.', 'Meera Nair'),
      v('pod_title', 'The pod the payout is for.', 'Sunday Badminton Doubles'),
      v('statement_type', 'Which kind of statement this is.', 'host payout'),
      v('venue_bill', 'The gross the split starts from, pre-formatted.', '₹2,400.00'),
      v('gst_amount', 'GST on the bill, pre-formatted.', '₹432.00'),
      v('duncit_label', 'What Duncit’s share is called on this statement.', 'Duncit Taken'),
      v('duncit_amount', 'Duncit’s share, pre-formatted.', '₹360.00'),
      v('payout_label', 'What the beneficiary’s share is called.', 'Your Payout'),
      v('payout_amount', 'What they are paid, pre-formatted.', '₹1,608.00'),
      v('approval_type', 'FULL or PARTIAL.', 'FULL'),
      v('reason', 'The approver’s note. Blank on a full approval.', ''),
    ],
  }),
  describeEmail({
    slug: 'payment-release-approved',
    name: 'Payment Release Approved',
    description:
      'Superseded by `payout-statement`, which is what `paymentRelease.notifyApproval` actually sends — this template has no send site and is kept only so an existing row is not orphaned.',
    audience: 'HOST',
    category: 'billing',
    fires: 'Nothing sends this today',
    subject: 'Payment release approved',
    footerNote: '',
    vars: [
      v('name', 'The beneficiary’s name.', 'Meera Nair'),
      v('release_type', 'What was released.', 'host payout'),
      v('pod_title', 'The pod it relates to.', 'Sunday Badminton Doubles'),
      v('approval_type', 'FULL or PARTIAL.', 'FULL'),
      v('amount_requested', 'What was asked for.', '2400.00'),
      v('approved_amount', 'What was approved.', '2400.00'),
      v('reason', 'The approver’s note.', ''),
    ],
  }),

  // --- Partner onboarding, the older meeting/interview flow -----------------
  describeEmail({
    slug: 'meeting-booked',
    name: 'Onboarding Meeting Booked',
    description:
      'Superseded by the per-party `<party>-onboarding-booked` templates, which is what the booking now sends. Kept so an existing row and its edits are not orphaned.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Nothing sends this any more — the per-party template does',
    subject: 'Your Duncit {{kind}} onboarding meeting is booked',
    footerNote: '',
    vars: meetingVars([MEETING_NOTES]),
  }),
  describeEmail({
    slug: 'meeting-scheduled',
    name: 'Onboarding Meeting Scheduled',
    description:
      'Superseded by the per-party `<party>-onboarding-interview` templates, which is what scheduling now sends. Kept so an existing row and its edits are not orphaned.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Nothing sends this any more — the per-party template does',
    subject: 'Your Duncit {{kind}} onboarding meeting is scheduled',
    footerNote: '',
    vars: meetingVars([MEETING_LINK, MEETING_NOTES]),
  }),
  describeEmail({
    slug: 'meeting-scheduled-admin',
    name: 'Onboarding Meeting Scheduled (staff copy)',
    description: 'The staff copy of a scheduled onboarding meeting.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'Staff schedules an onboarding meeting',
    subject: '{{kind}} onboarding meeting scheduled — {{name}}',
    footerNote: '',
    vars: meetingVars([
      v('email', 'The applicant’s address.', 'meera@example.com'),
      MEETING_LINK,
      MEETING_NOTES,
    ]),
  }),
  describeEmail({
    slug: 'meeting-rescheduled',
    name: 'Onboarding Meeting Details Updated',
    description:
      'The applicant, when staff edit the meeting’s link or instructions WITHOUT moving it. A move now sends the per-party `<party>-meeting-rescheduled` template, so this row is only ever reached with `change` set to `updated`.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Staff edit a scheduled meeting’s link or instructions without changing its time',
    subject: 'Your Duncit {{kind}} onboarding meeting details were updated',
    footerNote: '',
    vars: meetingVars([
      MEETING_LINK,
      MEETING_NOTES,
      v('change', 'Always `updated` — a move goes to the per-party template instead.', 'updated'),
      v('heading', 'The heading the service picks for the chosen `change`.', 'Your meeting details were updated'),
      v('intro', 'The opening line the service picks for the chosen `change`.', 'We’ve updated the details of your Venue onboarding meeting. Here’s the latest:'),
    ]),
  }),
  describeEmail({
    slug: 'meeting-cancelled',
    name: 'Onboarding Meeting Cancelled',
    description: 'The applicant, when the onboarding meeting is called off.',
    audience: 'HOST',
    category: 'notification',
    fires: 'An onboarding meeting is cancelled by staff or by the applicant',
    subject: 'Your Duncit {{kind}} onboarding meeting is cancelled',
    footerNote: '',
    vars: meetingVars([
      MEETING_NOTES,
      v('reason', 'The staff cancellation reason. Blank for a self-cancel.', 'We need to reschedule around a public holiday.'),
    ]),
  }),
  describeEmail({
    slug: 'meeting-approved',
    name: 'Onboarding Approved',
    description:
      'Superseded by the per-party `<party>-onboarding-approved` templates, which is what approval now sends. Kept so an existing row and its edits are not orphaned.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Nothing sends this any more — the per-party template does',
    subject: 'Your Duncit {{kind}} onboarding is approved 🎉',
    footerNote: '',
    vars: [
      v('name', 'The applicant’s first name.', 'Meera'),
      v('kind', 'Which onboarding this is.', 'Venue'),
    ],
  }),
  describeEmail({
    slug: 'meeting-rejected',
    name: 'Onboarding Rejected',
    description:
      'Superseded by the per-party `<party>-onboarding-rejected` templates, which is what rejection now sends. Kept so an existing row and its edits are not orphaned.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Nothing sends this any more — the per-party template does',
    subject: 'Update on your Duncit {{kind}} onboarding',
    footerNote: '',
    vars: [
      v('name', 'The applicant’s first name.', 'Meera'),
      v('kind', 'Which onboarding this is.', 'Venue'),
    ],
  }),
  describeEmail({
    slug: 'interview-applicant',
    name: 'Interview Application Received',
    description: 'The applicant, confirming their interview application landed.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Somebody applies through the interview form',
    subject: 'Your Duncit {{type}} application is received',
    footerNote: '',
    vars: [
      v('name', 'The applicant’s name.', 'Meera Nair'),
      v('type', 'What they applied as.', 'Venue Partner'),
      v('about', 'What they wrote about themselves.', 'We run two indoor courts in Noida.'),
      v('slots', 'The slots they offered, joined.', 'Mon 4:30 PM · Tue 11:00 AM'),
      v('ref', 'The application reference.', 'DUN-INT-0231'),
    ],
  }),
  describeEmail({
    slug: 'interview-admin',
    name: 'Interview Application (staff copy)',
    description: 'The staff copy of a new interview application.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'Somebody applies through the interview form',
    subject: 'New {{type}} application — {{name}}',
    footerNote: '',
    vars: [
      v('type', 'What they applied as.', 'Venue Partner'),
      v('name', 'The applicant’s name.', 'Meera Nair'),
      v('email', 'Their address.', 'meera@example.com'),
      v('phone', 'Their number.', '+91 98765 43210'),
      v('business', 'The business they represent.', 'Sector 62 Sports Arena'),
      v('about', 'What they wrote about themselves.', 'We run two indoor courts in Noida.'),
      v('slots', 'The slots they offered, joined.', 'Mon 4:30 PM · Tue 11:00 AM'),
      v('adminLink', 'Deep link to the application in the console.', 'https://admin.duncit.com/interviews/DUN-INT-0231'),
    ],
  }),
  describeEmail({
    slug: 'interview-scheduled',
    name: 'Interview Scheduled',
    description: 'The applicant, when their interview is confirmed.',
    audience: 'HOST',
    category: 'notification',
    fires: 'Staff schedules the interview',
    subject: 'Your Duncit {{type}} interview is scheduled',
    footerNote: '',
    vars: [
      v('name', 'The applicant’s name.', 'Meera Nair'),
      v('type', 'What they applied as.', 'Venue Partner'),
      v('slot', 'The confirmed slot, already formatted.', '26 Aug 2026, 4:30 PM'),
      v('link', 'The video-call link.', 'https://meet.google.com/abc-defg-hij'),
      v('ref', 'The application reference.', 'DUN-INT-0231'),
    ],
  }),

  // --- Host category requests ----------------------------------------------
  ...(
    [
      ['host-request-submitted', 'Host Request Submitted', 'A host applies to host a new category'],
      ['host-request-acknowledged', 'Host Request Acknowledged', 'A reviewer acknowledges the request'],
      ['host-request-approved', 'Host Request Approved', 'The request is approved and the category is granted'],
      ['host-request-rejected', 'Host Request Rejected', 'The request is turned down'],
    ] as const
  ).map(([slug, name, fires]) =>
    describeEmail({
      slug,
      name,
      description: `The applicant. ${fires}.`,
      audience: 'HOST',
      category: 'notification',
      fires,
      subject: `Your Duncit host request — ${name.replace('Host Request ', '').toLowerCase()}`,
      footerNote: '',
      vars: HOST_REQUEST_VARS,
    })
  ),

  // --- Venues ---------------------------------------------------------------
  describeEmail({
    slug: 'venue-slot-request',
    name: 'Venue Slot Request',
    description:
      'The venue owner, when a host asks for one of their slots. Carries one-tap approve and decline links. Its WhatsApp twin is VENUE_SLOT_REQUESTED, but the two are addressed separately because this one carries the decision URLs.',
    audience: 'VENUE',
    category: 'notification',
    fires: 'A host requests a venue availability slot',
    subject: 'New slot booking request — {{pod_title}}',
    footerNote: '',
    vars: [
      v('owner_name', 'The venue owner’s name.', 'Rohit'),
      v('venue_name', 'The venue being asked for.', 'Sector 62 Sports Arena'),
      v('pod_title', 'The pod that wants the slot.', 'Sunday Badminton Doubles'),
      v('host_name', 'The host asking.', 'Meera Nair'),
      v('when', 'The requested slot, already formatted.', 'Sun, 24 Aug 2026, 7:00 AM'),
      v('review_url', 'All pending requests in the Partners console.', 'https://partners.duncit.com/venues/requests'),
      v('approve_url', 'The decision page with Approve pre-selected.', 'https://partners.duncit.com/venues/requests/64f…?action=approve'),
      v('decline_url', 'The decision page with Decline pre-selected.', 'https://partners.duncit.com/venues/requests/64f…?action=decline'),
    ],
  }),

  // --- Listing and account status ------------------------------------------
  describeEmail({
    slug: 'brand-activated',
    name: 'Brand Activated',
    description: 'The brand owner, when their brand returns to the marketplace.',
    audience: 'ECOMM',
    category: 'notification',
    fires: 'A brand’s `is_active` is switched back on',
    subject: '{{brand_name}} is active on Duncit again',
    footerNote: '',
    vars: statusVars('contact_person', 'The brand’s contact person.', 'brand_name', 'The brand.', 'Ananya', 'Yonex'),
  }),
  describeEmail({
    slug: 'brand-deactivated',
    name: 'Brand Deactivated',
    description: 'The brand owner, when their brand and its products are hidden.',
    audience: 'ECOMM',
    category: 'notification',
    fires: 'A brand’s `is_active` is switched off',
    subject: '{{brand_name}} has been deactivated',
    footerNote: '',
    vars: statusVars('contact_person', 'The brand’s contact person.', 'brand_name', 'The brand.', 'Ananya', 'Yonex'),
  }),
  describeEmail({
    slug: 'product-activated',
    name: 'Product Activated',
    description: 'The listing owner, when their product returns to the marketplace.',
    audience: 'ECOMM',
    category: 'notification',
    fires: 'A product’s `is_active` is switched back on',
    subject: '{{product_name}} is active on Duncit again',
    footerNote: '',
    vars: statusVars('name', 'The listing owner.', 'product_name', 'The product.', 'Ananya', 'Yonex Mavis 350 Shuttlecock'),
  }),
  describeEmail({
    slug: 'product-deactivated',
    name: 'Product Deactivated',
    description: 'The listing owner, when their product is temporarily hidden.',
    audience: 'ECOMM',
    category: 'notification',
    fires: 'A product’s `is_active` is switched off',
    subject: '{{product_name}} has been deactivated',
    footerNote: '',
    vars: statusVars('name', 'The listing owner.', 'product_name', 'The product.', 'Ananya', 'Yonex Mavis 350 Shuttlecock'),
  }),
  describeEmail({
    slug: 'venue-activated',
    name: 'Venue Activated',
    description: 'The venue owner, when their venue is bookable again.',
    audience: 'VENUE',
    category: 'notification',
    fires: 'A venue’s `is_active` is switched back on',
    subject: '{{venue_name}} is active on Duncit again',
    footerNote: '',
    vars: statusVars('owner_name', 'The venue owner.', 'venue_name', 'The venue.', 'Rohit', 'Sector 62 Sports Arena'),
  }),
  describeEmail({
    slug: 'venue-deactivated',
    name: 'Venue Deactivated',
    description: 'The venue owner, when their venue is hidden from search and slot requests.',
    audience: 'VENUE',
    category: 'notification',
    fires: 'A venue’s `is_active` is switched off',
    subject: '{{venue_name}} has been deactivated',
    footerNote: '',
    vars: statusVars('owner_name', 'The venue owner.', 'venue_name', 'The venue.', 'Rohit', 'Sector 62 Sports Arena'),
  }),
  describeEmail({
    slug: 'host-activated',
    name: 'Host Activated',
    description: 'The host, when their account can create and run pods again.',
    audience: 'HOST',
    category: 'notification',
    fires: 'A host’s `is_active` is switched back on',
    subject: 'Your Duncit host account is active again',
    footerNote: '',
    vars: statusVars('host_name', 'The host.', 'host_email', 'The host’s address.', 'Meera', 'meera@example.com'),
  }),
  describeEmail({
    slug: 'host-deactivated',
    name: 'Host Deactivated',
    description: 'The host, when their account can no longer create pods.',
    audience: 'HOST',
    category: 'notification',
    fires: 'A host’s `is_active` is switched off',
    subject: 'Your Duncit host account has been deactivated',
    footerNote: '',
    vars: statusVars('host_name', 'The host.', 'host_email', 'The host’s address.', 'Meera', 'meera@example.com'),
  }),

  // --- Access grants --------------------------------------------------------
  describeEmail({
    slug: 'partner-access-granted',
    name: 'Partner Access Granted',
    description: 'The partner, when Host / Venue Partner / Club Admin / Product Seller access goes live.',
    audience: 'HOST',
    category: 'notification',
    fires: 'A partner role is granted to an account',
    subject: 'Your Duncit {{partner_type}} access is live 🎉',
    footerNote: '',
    vars: [
      v('name', 'The partner’s first name.', 'Meera'),
      v('partner_type', 'Which access was granted.', 'Venue Partner'),
      v('portal_url', 'The Partners console.', 'https://partners.duncit.com'),
      v('email', 'The account the access is attached to.', 'meera@example.com'),
    ],
  }),
  describeEmail({
    slug: 'admin-credentials',
    name: 'Admin Credentials',
    description: 'The first Super Admin, with the credentials the install generated.',
    audience: 'ADMIN',
    category: 'authentication',
    fires: 'The first Super Admin account is created',
    subject: 'Your Duncit Super Admin Credentials',
    footerNote: '',
    vars: [
      v('name', 'The admin’s name.', 'Suryansh'),
      v('email', 'The sign-in address.', 'admin@duncit.com'),
      v('password', 'The generated password. Read from the install, never stored in a template.', '••••••••'),
    ],
  }),
  describeEmail({
    slug: 'admin-access-granted',
    name: 'Admin Access Granted',
    description: 'An account, when it is granted admin access.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'An admin role is granted to an account',
    subject: 'Welcome to Duncit as an Admin',
    footerNote: '',
    vars: [v('name', 'The admin’s first name.', 'Suryansh')],
  }),
  describeEmail({
    slug: 'admin-access-revoked',
    name: 'Admin Access Revoked',
    description: 'An account, when its admin access is removed.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'An admin role is removed from an account',
    subject: 'Your Duncit admin access was removed',
    footerNote: '',
    vars: [v('name', 'The admin’s first name.', 'Suryansh')],
  }),
  describeEmail({
    slug: 'portal-access-approved',
    name: 'Portal Access Approved',
    description: 'The requester, when an admin approves their Jump-to-Portal request.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'A Jump-to-Portal access request is approved',
    subject: 'Your Duncit {{portal_name}} portal access is live 🎉',
    footerNote: '',
    vars: [
      v('name', 'The requester’s first name.', 'Suryansh'),
      v('portal_name', 'Which console.', 'Finance'),
      v('portal_url', 'The console’s URL.', 'https://finance.duncit.com'),
    ],
  }),
  describeEmail({
    slug: 'portal-access-declined',
    name: 'Portal Access Declined',
    description: 'The requester, when an admin declines their Jump-to-Portal request.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'A Jump-to-Portal access request is declined',
    subject: 'Your Duncit {{portal_name}} portal access request',
    footerNote: '',
    vars: [
      v('name', 'The requester’s first name.', 'Suryansh'),
      v('portal_name', 'Which console.', 'Finance'),
    ],
  }),
  describeEmail({
    slug: 'signed-contract',
    name: 'Signed Contract',
    description: 'The counter-party, with the signed PDF attached — a link would need them to hold a Legal-portal account.',
    audience: 'ADMIN',
    category: 'internal',
    fires: 'A contract is signed and shared from the Legal portal',
    subject: 'Signed contract: {{contract_name}}',
    footerNote: '',
    vars: [
      v('contract_name', 'The contract.', 'Venue Partnership Agreement 2026'),
      v('sender_name', 'Who sent it.', 'Suryansh Srivastava'),
      v('message', 'The covering note. May be blank.', 'Countersigned copy attached.'),
    ],
  }),

  // --- Inbound conversations -------------------------------------------------
  describeEmail({
    slug: 'contact-received',
    name: 'Contact Received',
    description: 'Whoever wrote in through the website contact form.',
    audience: 'PUBLIC',
    category: 'support',
    fires: 'The website contact form is submitted',
    subject: 'We received your message — {{app_name}}',
    footerNote: '',
    vars: [
      v('name', 'Who wrote in.', 'Aarav Sharma'),
      v('subject', 'What they wrote about.', 'Partnership enquiry'),
      v('message', 'What they wrote.', 'We would like to list our arena on Duncit.'),
      v('logo_url', 'The brand logo, passed by the send site.', 'https://cdn.duncit.com/logo.png'),
    ],
  }),
  describeEmail({
    slug: 'faq-received',
    name: 'FAQ Question Received',
    description: 'Whoever asked a question through the FAQ form, when they left an address.',
    audience: 'PUBLIC',
    category: 'support',
    fires: 'The FAQ question form is submitted with an address',
    subject: 'We received your question — {{app_name}}',
    footerNote: '',
    vars: [
      v('question', 'What they asked.', 'How do refunds work if a pod is cancelled?'),
      v('logo_url', 'The brand logo, passed by the send site.', 'https://cdn.duncit.com/logo.png'),
    ],
  }),
  describeEmail({
    slug: 'grievance-received',
    name: 'Grievance Received',
    description: 'The complainant. The reference number in it is the only proof they have that they raised it.',
    audience: 'PUBLIC',
    category: 'legal',
    fires: 'A grievance is submitted',
    subject: '{{grievance_no}} — {{app_name}}',
    footerNote: '',
    vars: [
      v('name', 'The complainant.', 'Aarav Sharma'),
      v('grievance_no', 'The reference to quote in any follow-up.', 'DUN-GRV-0042'),
      v('subject', 'What the grievance is about.', 'Refund not received'),
      v('description', 'What they told us.', 'The pod was cancelled on 12 Aug and no refund has arrived.'),
      v('officer_block', 'The Grievance Officer’s name and contact, joined by the service.', 'Priya Menon · grievance@duncit.com'),
      v('logo_url', 'The brand logo, passed by the send site.', 'https://cdn.duncit.com/logo.png'),
    ],
  }),
  describeEmail({
    slug: 'newsletter-welcome',
    name: 'Newsletter Welcome',
    description: 'A new newsletter subscriber. Marketing, so the footer carries the unsubscribe line.',
    audience: 'PUBLIC',
    category: 'marketing',
    fires: 'Somebody subscribes to the newsletter',
    subject: 'Welcome to {{app_name}}',
    footerNote: '',
    vars: [
      v('email', 'The subscribed address.', 'aarav@example.com'),
      v('site_url', 'Where they subscribed.', 'https://duncit.com'),
      v('logo_url', 'The brand logo, passed by the send site.', 'https://cdn.duncit.com/logo.png'),
    ],
  }),
];
