export { AppLocaleProvider } from './AppLocaleProvider';
export { DuncitLocalizationProvider } from './DuncitLocalizationProvider';
export type { DuncitLocalizationProviderProps } from './DuncitLocalizationProvider';
export { PUBLIC_APP_SETTINGS, useDateFormat } from './useDateFormat';
export type { DateInput, UseDateFormatOptions } from './useDateFormat';
export { PUBLIC_FEATURE_FLAGS, useFeatureFlag, useFeatureFlags } from './useFeatureFlag';
export { applyPageMeta, pageTitle, usePageMeta } from './usePageMeta';
export type { PageMetaInput } from './usePageMeta';
export { useSession } from './useSession';
export type { SessionValue } from './useSession';
// The session shape and its pure derivations, re-exported so a surface reads
// one package rather than importing @duncit/user-core alongside this one.
export {
  accountEmail,
  accountName,
  can,
  canAny,
  hasAppAccess,
  initials,
  normalizeMe,
  type FeatureFlags,
  type SessionDevice,
  type SessionSnapshot,
  type SessionStatus,
  type SessionUser,
} from '@duncit/user-core';
// Re-exported so every portal gets the shared clock/formatter from one place.
export {
  DEFAULT_TIME_SOURCE,
  TIME_SOURCES,
  ambientDateFormat,
  ambientDateFormatter,
  ambientTimeFormat,
  createClock,
  createDateFormatter,
  formatDate,
  formatDateTime,
  formatDay,
  formatTime,
  isPickerSafeFormat,
  muiDateFormats,
  setAmbientDateSettings,
  subscribeAmbientDateSettings,
  unsupportedPickerTokens,
  usesTwelveHourClock,
  resetServerTimeStamp,
  stampServerTime,
  resolveActiveOccasion,
  resolveNow,
  toEpochMs,
  toTimeSource,
  type Clock,
  type ClockInput,
  type DateFormatter,
  type OccasionWindow,
  type TimeSource,
} from '@duncit/datetime';
export {
  LocaleProvider,
  PUBLIC_LOCALES,
  PUBLIC_TRANSLATIONS,
  useTranslation,
} from './useTranslation';
export {
  ADMIN_BUNDLE,
  ADS_BUNDLE,
  AI_BUNDLE,
  AI_MONITORING_BUNDLE,
  CHALLENGE_BUNDLE,
  CONTENT_REPORT_BUNDLE,
  CRM_BUNDLE,
  DEVELOPERS_BUNDLE,
  allFallbackEntries,
  createTranslator,
  FINANCE_BUNDLE,
  flattenCatalogue,
  GRIEVANCE_BUNDLE,
  LEGAL_BUNDLE,
  MAIL_PREFERENCE_BUNDLE,
  mailCategoryCopy,
  MEDIA_BUNDLE,
  mergeCatalogues,
  missingKeys,
  MWEB_BUNDLE,
  nestCatalogue,
  PARTNERS_BUNDLE,
  POD_PRODUCT_BUNDLE,
  POLICY_ACCEPTANCE_BUNDLE,
  PRODUCTS_BUNDLE,
  policyAcceptanceMethodLabel,
  resolveLocale,
  SHELL_BUNDLE,
  MARKETING_BUNDLE,
  ONBOARDING_BUNDLE,
  POD_FORM_BUNDLE,
  CLUB_FORM_BUNDLE,
  POD_DETAILS_BUNDLE,
  SUPPORT_BUNDLE,
  TECH_BUNDLE,
  SURFACE_BUNDLES,
  WEBSITE_APP_BUNDLE,
  WEBSITE_BUNDLE,
  WHATSAPP_BUNDLE,
  whatsappCategoryCopy,
  type FlatCatalogue,
  type Locale,
  type MailCategoryCopy,
  type NestedCatalogue,
  type PolicyMethodTranslate,
  type Translator,
  type WaCategoryCopy,
} from '@duncit/i18n';
